Cargo.lock
api/Cargo.toml
api/src/server.rs

refactor: axum -> actix

---

Cargo.lock
spog/README.md
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/components/common.rs
spog/ui/src/components/deps.rs
spog/ui/src/components/mod.rs
spog/ui/src/pages/chicken.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/package/mod.rs
spog/ui/src/pages/package/search/mod.rs
spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/vulnerability.rs

Mainly cleaning up some stuff, minor fixes, common component, and trying to make it more clear (type vs type).

refactor: tweak the UI a bit

---

vexination/index/src/lib.rs

- Use STRING indexing options for identifiers
- Add packages field based on known affected product ids
- Add CVE field based on CVE identifier

feat: add more fields to vexination index

---

spog/search/src/server.rs
spog/search/src/vuln.rs
vexination/index/src/lib.rs
vexination/index/src/search.rs

- use boolean occurence queries for match and partial match
- use boolean union and intersection of terms for And, Or and Not

feat: generate tantivy query tree from sikula

---

Cargo.lock
Cargo.toml
DEVELOPING.md
bombastic/api/src/lib.rs
bombastic/api/src/server.rs
bombastic/index/Cargo.toml
bombastic/index/src/lib.rs
bombastic/index/src/search.rs
bombastic/indexer/Cargo.toml
bombastic/indexer/src/indexer.rs
bombastic/indexer/src/lib.rs
index/Cargo.toml
index/src/lib.rs
spog/api/Cargo.toml
spog/api/src/search/mod.rs
spog/api/src/search/sbom.rs
vexination/index/src/lib.rs

* add support for indexing cyclonedx SBOM
* add support for querying index in spog api

feat: replace sqlite index with search index in bombastic

---

.gitignore
Cargo.lock
deploy/compose/compose-trustification.yaml
exporter/Cargo.toml
exporter/src/exporter.rs
exporter/src/lib.rs
exporter/src/main.rs
trust/Cargo.toml
trust/src/main.rs

First implementation of sbom exporter to guac

feat: Implement guac exporter

---

DEVELOPING.md
bombastic/api/src/server.rs

Next up is better error-to-response mappings

refactor: clean up some of the actix config

---

.github/workflows/containers.yaml
.github/workflows/publish.yaml
Cargo.lock
README.md
bombastic/index/src/lib.rs
bombastic/index/src/search.rs
deploy/k8s/bombastic/api/051-Route.yaml
deploy/k8s/spog/api/051-Route.yaml
deploy/k8s/spog/ui/030-Deployment.yaml
deploy/k8s/vexination/api/051-Route.yaml
docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/admin/nav.adoc
docs/modules/admin/pages/index.adoc
docs/modules/admin/pages/installing.adoc
docs/modules/admin/pages/openapi.adoc
docs/modules/user/nav.adoc
docs/modules/user/pages/index.adoc
docs/modules/user/pages/retrieve.adoc
spog/ui/src/components/advisory.rs
vexination/index/Cargo.toml
vexination/index/src/lib.rs

- chore: rename spog-ui -> trust-ui
- feat: add subdomains for APIs
- feat: improve bombastic search experience
- fix: remove highest score column
- docs: add initial asciidoc documentation

Various improvements and documentation

---

.github/workflows/ci.yaml
.github/workflows/integration.yaml
Cargo.lock
Cargo.toml
DEVELOPING.md
bombastic/api/src/lib.rs
bombastic/api/src/server.rs
bombastic/indexer/src/indexer.rs
bombastic/indexer/src/lib.rs
deploy/compose/compose.yaml
event-bus/src/kafka.rs
event-bus/src/lib.rs
integration-tests/Cargo.toml
integration-tests/src/lib.rs
integration-tests/tests/bombastic.rs
integration-tests/tests/vexination.rs
vexination/api/src/lib.rs
vexination/indexer/src/lib.rs

* Create integration-tests module where test infrastructure and tests live.
* Add integration test for bombastic that tests API, indexing and search.
* Ensure indexer starts from earliest offset to catch previous changes.

feat: add integration tests

---

Cargo.lock
bombastic/api/Cargo.toml
bombastic/api/src/server.rs
bombastic/model/src/search.rs
spog/ui/dev/endpoints/backend.json
spog/ui/src/backend/mod.rs
spog/ui/src/console.rs
vexination/api/Cargo.toml
vexination/api/src/server.rs
vexination/model/src/search.rs

- feat: improve bombastic API description
- feat: add openapi to vexination API
- feat: provide links to bombastic and vexination openapi

OpenAPI for Vexination

---

Cargo.lock
Cargo.toml
spog/api/Cargo.toml
spog/api/build.rs
spog/api/src/index.rs
spog/api/src/lib.rs
spog/api/src/server.rs
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/build.rs
spog/ui/src/about.rs
spog/ui/src/backend/mod.rs
spog/ui/src/backend/version.rs
version/Cargo.toml
version/src/build.rs
version/src/lib.rs
version/src/version.rs

This adds versioning information infrastructure to the project, adding an endpoint to SPOG API, and leveraging the feature and backend endpoint in the UI to show the frontend and backend information.
closes #138

feat: add version information

---

docs/modules/ROOT/pages/index.adoc

Minor edits to sentence structure, and grammar fixes.

Update to intro doc text

---

.gitignore
Cargo.lock
bombastic/index/Cargo.toml
bombastic/model/Cargo.toml
index/Cargo.toml
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/backend/version.rs
spog/ui/src/components/advisory.rs
spog/ui/src/components/backend.rs
spog/ui/src/components/catalog/mod.rs
vexination/index/Cargo.toml
vexination/index/src/lib.rs

Also:
* fix a button rendering issue
* fix a caching issue

Allow searching with NOT, AND, OR and ()

---

bombastic/index/src/lib.rs
index/src/lib.rs
vexination/index/src/lib.rs

Boost the relevance score of certain fields to ensure matches within
those fields rank higher.

feat: tune relevance of some fields

---

bombastic/api/src/lib.rs
bombastic/api/src/server.rs
vexination/api/src/lib.rs
vexination/api/src/server.rs

also deleted a bit of unused code

refactor: configure middleware with the handlers that depend on it

---

spog/api/src/search.rs

fix: don't fail with omitted search string

---

bombastic/api/src/lib.rs
bombastic/walker/src/lib.rs
bombastic/walker/src/shell_wrap.rs
bombastic/walker/walker.sh
vexination/api/src/lib.rs

- fix: set secret from env
- feat: add support for providing bombastic api key

bombastic api key

---

bombastic/api/src/server.rs
vexination/api/src/server.rs

fix: add body param to swagger-ui for uploads

---

vexination/index/src/lib.rs
vexination/index/src/search.rs
vexination/model/src/search.rs

- fix: search for aggregated severity
- fix: support partial matches of packages

vex index fix

---

README.md
deploy/compose/.env
deploy/compose/compose-guac.yaml
deploy/compose/compose-trustification.yaml
deploy/compose/compose-walkers.yaml

* Add bombastic-walker process
* Add spog-ui process
* Fix command line arguments
* Require setting TRUST_VERSION externally and update docs

fix: update compose file

---

README.md
deploy/compose/compose-guac.yaml
deploy/compose/compose-trustification.yaml
deploy/compose/compose-walkers.yaml

Also fixed the VEX API link in the spog

fix: make TRUST_VERSION mandatory

---

README.md

docs: note minimum required podman-compose version

---

bombastic/api/src/server.rs
bombastic/model/src/search.rs
bombastic/testdata/ubi9-sbom.json
index/src/lib.rs
integration-tests/tests/bombastic.rs

There seems to be a lot more info in the version than the name.

feat: search version by default

---

spog/api/src/config/default.yaml
spog/api/src/config/schema.yaml
spog/model/Cargo.toml
spog/model/src/config.rs
spog/ui/src/backend/mod.rs
spog/ui/src/components/search/dynamic.rs
spog/ui/src/components/search/simple.rs

feat: add a way to add dividers to filter groups

---

spog/ui/src/hooks/search.rs

When navigating back from the previous page, the state is populated from the history API. However, the component's state wasn't properly initialized.

fix: populate components when navigating back

---

bombastic/model/src/search.rs
index/src/metadata.rs
spog/api/src/advisory.rs
spog/api/src/sbom.rs
spog/api/src/server.rs
spog/model/src/pkg.rs
spog/model/src/search.rs
spog/ui/src/backend/vuln.rs
vexination/model/src/search.rs

This makes the data available in the SPoG UI (internally)

chore: bring metadata into the spog ui too

---

spog/api/src/config/default.yaml
spog/api/src/config/schema.yaml
spog/model/Cargo.toml
spog/model/src/config.rs
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/components/common.rs
spog/ui/src/console.rs

Besides a few tweaks, this adds the ability to customize the docs link, which can we do in the deployment. Pointing the user to the right documentation.

refactor: add some tweaks for the base page components

---

deploy/compose/compose-trustification.yaml

Added ISSUER_URL under spog_ui environment variables

Added ISSUER_URL to the podman compose file

---

deploy/compose/compose.yaml

- fix: use older keycloak version with working healthcheck

keycloak mods

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/components/search/simple.rs

JIRA: https://issues.redhat.com/browse/TC-353

fix: fix layout issue with overlapping switch component

---

bombastic/api/src/lib.rs
bombastic/api/src/server.rs
infrastructure/src/app.rs
infrastructure/src/lib.rs
vexination/api/src/lib.rs
vexination/api/src/server.rs

This builds on top of: https://github.com/trustification/trustification/pull/346
On the last commit is relevant and this PR should only be merged after merging  https://github.com/trustification/trustification/pull/346

Make the swagger UI and openapi spec public/no-auth

---

spog/ui/src/components/advisory/mod.rs
spog/ui/src/utils/csaf.rs
spog/ui/test-data/quarkus1.json

This PR is based on #346 and should be merged after it. Only the last commit is relevant for this PR.

Fix the issue of "invalid product ID"

---

Cargo.lock
auth/src/authenticator/error.rs
common/Cargo.toml
common/src/error.rs
common/src/lib.rs
common/src/reqwest.rs
spog/api/Cargo.toml
spog/api/src/analyze.rs
spog/api/src/config/schema.yaml
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/backend/analyze.rs
spog/ui/src/backend/error.rs
spog/ui/src/backend/mod.rs
spog/ui/src/components/error.rs
spog/ui/src/pages/scanner/inspect.rs
spog/ui/src/pages/scanner/mod.rs

Also, add a button to perform another SBOM scan.
Screenshot:

refactor: improve the error reporting a bit, especially with CRDA

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml

Closes: https://issues.redhat.com/browse/TC-364

In the paging search text box, after entering a number we need to press Enter twice for the desired page to be displayed

---

integration-tests/src/lib.rs
integration-tests/tests/bombastic.rs

This PR includes test scripts for
- unauthorized POST and DELETE request
- forbidden POST and DELETE request
- Invalid and missing input for GET request.

Integration tests for bombastic api access and get call

---

v11y/api/src/db/mod.rs
v11y/client/src/lib.rs

Apply better tests.
Sign my commits.

Change to using sets instead of vectors.

---

index/src/lib.rs
integration-tests/src/lib.rs

Related to https://github.com/trustification/trustification.dev/issues/27

feat: make index size configurable

---

integration-tests/src/bom.rs
integration-tests/src/lib.rs
integration-tests/src/spog.rs
integration-tests/src/vex.rs

No functional changes, just keeping related things together

refactor: reorganize the integ services a bit

---

indexer/src/lib.rs

fix: ensure keys are sent to indexed topic after snapshot is published

---

integration-tests/src/bom.rs
integration-tests/src/lib.rs
integration-tests/src/spog.rs
integration-tests/src/vex.rs
integration-tests/tests/bombastic.rs
integration-tests/tests/spog.rs
integration-tests/tests/vexination.rs

in preparation for testing against remote deployments #401

refactor: give test contexts a base url instead of a port

---

DEVELOPING.md
integration-tests/README.md
integration-tests/src/config.rs

feat: minor naming tweaks and docs for integs

---

Cargo.lock
Cargo.toml
index/Cargo.toml
spog/ui/Cargo.toml
storage/Cargo.toml

fixes #458
There's still a snyk-rs fork... move that too?

fix: move a few forks over to the trustification org

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/src/components/advisory/mod.rs
spog/ui/src/components/content.rs
spog/ui/src/components/editor.rs
spog/ui/src/components/markdown.rs
spog/ui/src/components/mod.rs
spog/ui/src/components/sbom/mod.rs
spog/ui/src/components/table_wrapper.rs
spog/ui/src/pages/scanner/inspect.rs
spog/ui/src/pages/scanner/upload.rs
spog/ui/styles/main.scss

Working towards design goals, including:
* Disabling row expansion in SBOMs (which was always empty)
* Change column header labels
* Re-use the new code editor in other locations
* Parse/render markdown for CSAF note fields

Improve UI

---

Cargo.lock
bombastic/index/Cargo.toml
bombastic/index/src/lib.rs
bombastic/model/Cargo.toml
index/Cargo.toml
spog/ui/Cargo.toml
vexination/index/Cargo.toml
vexination/index/src/lib.rs
vexination/model/Cargo.toml

fix: keep sorting config for empty queries

---

docs/modules/user/pages/bombastic.adoc

Wrote a procedure to create SBOM files by using the Syft tool.
Fixes: Jira [TC-534](https://issues.redhat.com/browse/TC-534)

docs: Added a procedure for creating SBOM files

---

index/src/lib.rs
indexer/src/lib.rs

Rather than reindexing after syncing the existing index, start fresh to ensure old files get cleaned out.

fix: reindex starting from an empty index

---

deploy/compose/.env

This image should contain all changes neccessary to run SBOM walker with Guac.
What I tested it with is:
* Run the core components and Guac
```
docker compose -f compose.yaml -f compose-trustification.yaml -f compose-guac.yaml up --force-recreate
```
* Run SBOM walker manually
```
RUST_LOG=info cargo run -p trust bombastic walker --bombastic-url http://localhost:8082 --oidc-client-id walker --oidc-client-secret ZVzq9AMOVUdMY1lSohpx1jI3aW56QDPS --oidc-issuer-url http://localhost:8090/realms/chicken
```
Note that ingesting will take much longer than walker process. You should see log like this for every SBOM
```
compose-guac-ingestor-1        | {"level":"info","ts":1694439018.6327646,"caller":"process/process.go:218","msg":"Decoding document with encoding:  BZIP2"}
compose-vexination-api-1 …
```

Upgrade trustification image

---

Cargo.lock
event-bus/src/lib.rs
event-bus/src/sqs.rs
index/src/lib.rs
indexer/Cargo.toml
indexer/src/lib.rs

- chore: refactor event bus to not require lifetimes
- fix: retries for reindexing

reindex retries

---

docs/modules/user/pages/search.adoc
docs/modules/user/pages/vexination.adoc
spog/api/src/config/default.yaml
vexination/index/src/lib.rs
vexination/model/src/search.rs

fix: separate advisory and cve dates

---

Cargo.lock
bombastic/api/src/lib.rs
bombastic/indexer/src/lib.rs
bombastic/walker/src/lib.rs
bommer/src/main.rs
collector/nvd/src/lib.rs
collector/osv/src/lib.rs
collector/snyk/src/lib.rs
collectorist/api/src/coordinator/mod.rs
collectorist/api/src/lib.rs
exhort/api/src/lib.rs
exporter/src/lib.rs
infrastructure/Cargo.toml
infrastructure/src/health/checks.rs
infrastructure/src/health/mod.rs
infrastructure/src/infra.rs
infrastructure/src/lib.rs
spog/api/src/lib.rs
v11y/api/src/lib.rs
vexination/api/src/lib.rs
vexination/indexer/src/lib.rs
vexination/walker/src/lib.rs

This adds some real health checks to the infrastructure. It also makes use of them for collectors and collectorist.

Add real health checks

---

indexer/src/lib.rs
storage/src/lib.rs

Fix an issue with the previous fix where the stream would not continue properly on errors.
This time, use the builting continuation mechanism in the s3 api to start fetching from the last continuation token. This way errors we can continue reindexing from the last 'completed stage' even if errors arise from non-s3 errors.

fix: recreate stream from last page on object retrieval errors

---

docs/modules/user/pages/bombastic.adoc
docs/modules/user/pages/vexination.adoc

The bullet point format was broken, but now it should be fixed.

docs : Fixed bullet point formatting

---

Cargo.lock
deploy/compose/compose-walkers.yaml
vexination/walker/Cargo.toml
vexination/walker/src/lib.rs
vexination/walker/src/server.rs

fix: vex walker publishes to api url instead of directly to storage

---

Cargo.lock
vexination/walker/Cargo.toml
vexination/walker/src/lib.rs
vexination/walker/src/server.rs

fix: add oidc params to vex walker

---

collector/nvd/src/lib.rs
collector/nvd/src/server.rs
collector/osv/src/lib.rs
collector/osv/src/server.rs
collector/snyk/src/lib.rs
collector/snyk/src/server.rs
collectorist/api/src/coordinator/collector.rs
deploy/compose/compose-collectors.yaml
deploy/compose/container_files/collectorist/collectorist.yaml
deploy/k8s/chart/templates/collector/nvd/030-Deployment.yaml
deploy/k8s/chart/templates/collector/osv/030-Deployment.yaml
deploy/k8s/chart/templates/collector/snyk/030-Deployment.yaml
trust/Containerfile

Enhance helm charts similarly for missed GUAC_URL. Adjust collectors to accept --guac-url/GUAC_URL since no longer provided by collectorist.

Adjust compose files for collector(ist) changes.

---

bombastic/walker/src/lib.rs
bombastic/walker/src/processing.rs
bombastic/walker/src/scanner.rs

fix: actually evaluate the fix flag

---

deploy/k8s/chart/templates/bombastic/walker/030-Deployment.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Set interval to once every day

fix: make walker interval adjustable

---

deploy/openshift/Makefile
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

- feat: enable guac in openshift template
- feat: enable guac in app-sre

enable guac in openshift

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/exporter/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/walker/030-CronJob.yaml
deploy/k8s/chart/templates/collector/nvd/030-Deployment.yaml
deploy/k8s/chart/templates/collector/osv/030-Deployment.yaml
deploy/k8s/chart/templates/collector/snyk/030-Deployment.yaml
deploy/k8s/chart/templates/collectorist/api/030-Deployment.yaml
deploy/k8s/chart/templates/exhort/api/030-Deployment.yaml
deploy/k8s/chart/templates/spog/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/walker/030-CronJob.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
indexer/src/lib.rs

Allow configuring log level of all components in openshift template.

fix: make log level configurable in helm values

---

indexer/src/lib.rs

Slightly change the semantics of the indexed queue so that it includes the full event metadata, and rather than indicating a successful indexing, it contains the full event. This allows chaining other processes on the indexed queue that want to react to events that are processed by the indexer (even if failed).

feat: propagate s3 events to indexed queue

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/common/src/utils/cvss.rs
spog/ui/crates/common/src/utils/mod.rs
spog/ui/crates/components/src/cvss.rs
spog/ui/crates/components/src/theme.rs
spog/ui/src/app.rs
spog/ui/src/console/mod.rs

feat: implement CVSS indicator from sketches

---

Cargo.lock

Includes fix for vexination-walker

fix: update dependencies

---

.github/workflows/integration.yaml
Cargo.toml
integration-tests/tests/ui.rs
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/README.md
spog/ui/crates/common/src/utils/search.rs
spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/advisory/search.rs
spog/ui/crates/components/src/cve/search.rs
spog/ui/crates/components/src/hooks/search.rs
spog/ui/crates/components/src/sbom/search.rs
spog/ui/crates/components/src/search/dynamic.rs
spog/ui/crates/components/src/search/simple.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/search.rs
version/src/lib.rs
xtask/src/task/test.rs

This change fixes two issues with the page state:
* the defaults/initial terms are not applied properly
* the page state sometimes isn't serialized/stored

fix: inconsistent page state

---

deploy/k8s/dashboards/trustification-performance.json
deploy/k8s/dashboards/trustification-slos.json
v11y/api/src/server/mod.rs
v11y/api/src/server/search.rs
v11y/client/src/lib.rs

* Consolidate panels for performance metrics to make it easier to get the overview
* Change v11y search path to /api/v1/vulnerability/search

feat: add v11y to dashboards

---

spog/api/src/config/default.yaml

fix: update filters after purl changes in SBOM

---

Cargo.lock
collector/snyk/Cargo.toml
collector/snyk/src/lib.rs
collector/snyk/src/rewrite.rs
collector/snyk/src/server.rs

Rewrite RHEL pURLs towards a format expected by Snyk.

Improvement for #682

---

integration-tests/run-test-binaries.sh

This caused the integration tests to pass in the production environment 🙄

fix: fail test run if tests fail

---

Cargo.lock
collector/client/src/lib.rs
collector/osv/Cargo.toml
collector/osv/src/client/mod.rs
collector/osv/src/server.rs
collectorist/api/src/server/collect.rs
collectorist/client/Cargo.toml
collectorist/client/src/lib.rs
exhort/api/Cargo.toml
exhort/api/src/server.rs
exhort/model/src/lib.rs
spog/api/src/sbom/vuln.rs
v11y/client/Cargo.toml
v11y/client/src/lib.rs

through collectorist and up to exhort and the analyze request.

Improve error-handling from collectors (OSV only thus far)

---

deploy/compose/compose-trustification.yaml
deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/openshift/template.yaml
integration-tests/tests/bombastic.rs

fix: add sbom validator to deployments

---

integration-tests/src/bom.rs
integration-tests/tests/bombastic.rs

pedantry: i don't love the explicit boolean literals

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Use a longer interval for production since the index is bigger and takes longer.

fix: parameterize index sync interval

---

deploy/k8s/chart/templates/bombastic/walker/030-CronJob.yaml
deploy/k8s/chart/templates/config/020-ConfigMap.yaml
deploy/k8s/chart/templates/v11y/walker/020-PersistentVolumeClaim.yaml
deploy/k8s/chart/templates/v11y/walker/030-CronJob.yaml
deploy/k8s/chart/templates/vexination/walker/030-CronJob.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Expose suspend through openshift template

feat: allow suspending the walker cronjob

---

spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/sbom_report/mod.rs

- Donut chart and dates next to each other
- remove "SBOM detail information" text from title

SPog UI: Sbom Report enhancements

---

Cargo.lock
bombastic/api/src/lib.rs
deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml
infrastructure/Cargo.toml
infrastructure/src/app/http.rs
infrastructure/src/app/mod.rs
infrastructure/src/infra.rs
infrastructure/src/tracing.rs
integration-tests/src/bom.rs
integration-tests/src/spog.rs
integration-tests/src/vex.rs
spog/api/src/server.rs
v11y/api/src/lib.rs
vexination/api/src/lib.rs

* Modify from boolean to enum to keep code and yaml in sync

fix: configure tracing on HTTP server

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/spog/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/openshift/template.yaml

@ctron With these changes Jaeger tracing should work.

fix: add remaining annotations for jaeger

---

spog/api/src/advisory.rs
spog/api/src/analyze.rs
spog/api/src/config/mod.rs
spog/api/src/cve.rs
spog/api/src/endpoints.rs
spog/api/src/guac/service.rs
spog/api/src/sbom/vuln.rs
spog/api/src/server.rs

This PR adds some more tracing and parallelizes guac queries in batches of 4

more tracing & parallelize guac queries

---

integration-tests/tests/spog.rs

Fixes #696
Prevents stale VEX documents with a matching CPE id from correlating the test fixture's SBOM with more than one VEX.

fix: uniquify the cpe identifier in the correlation integ

---

Cargo.lock
bombastic/index/Cargo.toml
bombastic/index/src/lib.rs
bombastic/model/src/search.rs
spog/api/src/sbom/get.rs
spog/api/src/sbom/search.rs

feat(bombastic): index sha256 and spdx doc namespace

---

integration-tests/tests/spog.rs

Fixes #618
We wait on guac up to the ntest::timeout value, 30s. This should account for a slow-to-start-up guac container.

fix: deunstable the spog_dependencies integ test

---

bombastic/walker/src/lib.rs
bombastic/walker/src/scanner.rs
deploy/k8s/chart/templates/bombastic/walker/020-PersistentVolumeClaim.yaml
deploy/k8s/chart/templates/bombastic/walker/030-CronJob.yaml
deploy/k8s/chart/templates/vexination/walker/020-PersistentVolumeClaim.yaml
deploy/k8s/chart/templates/vexination/walker/030-CronJob.yaml
deploy/openshift/template.yaml
vexination/walker/src/lib.rs
vexination/walker/src/server.rs

Reduces network traffic and resources spent on bombastic and vexination walkers in a long running environment.
v11y requires more changes followed up in a separate PR

feat: support incremental walking

---

Cargo.lock
api/Cargo.toml
auth/Cargo.toml
bombastic/api/Cargo.toml
bombastic/model/Cargo.toml
collector/nvd/Cargo.toml
collector/osv/Cargo.toml
collector/snyk/Cargo.toml
collectorist/api/Cargo.toml
exhort/api/Cargo.toml
exhort/model/Cargo.toml
spog/api/Cargo.toml
spog/api/src/sbom/search.rs
spog/api/src/sbom/vuln.rs
spog/example-data/cve-2023-22998.json
spog/model/Cargo.toml
spog/model/src/csaf.rs
spog/model/src/vuln.rs
spog/ui/Cargo.lock
spog/ui/crates/components/src/spdx/packages.rs
spog/ui/src/pages/sbom_report/details.rs
v11y/api/Cargo.toml
v11y/model/Cargo.toml
version/Cargo.toml
vexination/api/Cargo.toml
vexination/model/Cargo.toml

Also:
* Update Utoipa to 4 (as https://github.com/juhaku/utoipa/issues/631 didn't get backported)
* Render versions comma seperated

Add remediations

---

Cargo.lock
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/components/src/advisory/details/mod.rs
spog/ui/crates/components/src/advisory/details/remediation.rs
spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/crates/components/src/search/simple.rs
spog/ui/crates/components/src/spdx/mod.rs
spog/ui/crates/components/src/spdx/packages.rs
spog/ui/src/hooks.rs
spog/ui/src/main.rs
spog/ui/src/pages/cve/result/mod.rs
spog/ui/src/pages/package/result/versions.rs
spog/ui/src/pages/sbom_report/details/cve.rs
spog/ui/src/pages/sbom_report/details/mod.rs

* Fix #738
* add relevant advisories to CVE details section
* update `segment` dependency, to get rid of empty batcher messages

Bug fixes and performance improvements

---

spog/ui/src/console/mod.rs

fix: only disable search pages if dedicated search is disabled

---

spog/ui/crates/components/src/cve/mod.rs
spog/ui/crates/components/src/lib.rs
spog/ui/crates/components/src/pagination.rs
spog/ui/src/pages/cve/result/products.rs
spog/ui/src/pages/sbom_report/details/mod.rs
spog/ui/src/pages/search.rs

JIRA: https://issues.redhat.com/browse/TC-661

Tweak label and re-use component

---

spog/api/src/config/default.yaml
spog/model/src/config.rs
spog/ui/src/console/mod.rs

https://issues.redhat.com/browse/TC-621

Add Jira to sidebar -> support label

---

deploy/k8s/chart/templates/bombastic/collector/030-CronJob.yaml
deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/collector/030-CronJob.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Not yet tested, may need additional tuning

fix: add resources limits for guac and collectors

---

Cargo.lock
spog/api/src/advisory.rs
spog/api/src/app_state.rs
spog/api/src/cve.rs
spog/api/src/lib.rs
spog/api/src/sbom/get.rs
spog/api/src/sbom/search.rs
spog/api/src/sbom/vuln.rs
spog/api/src/server.rs
spog/api/src/service/v11y.rs
v11y/client/Cargo.toml
v11y/client/src/lib.rs

* Add trace context propagation to v11y
* extract `AppState` from `server` module into its own
* Fix an issue when a v11y isn't URL safe

A bit of cleanup and refactoring

---

spog/api/src/endpoints/analyze.rs

fix: add CRDA headers, as far as possible

---

spog/ui/crates/components/src/packages/mod.rs

We already had a component like this, which looked visually different. And during on of the UX calls, we went away from "green" as a color for a vulnerability.

refactor: re-use existing component

---

integration-tests/tests/spog.rs

30s may not be enough time for the compose stuff to settle
#618

fix: applying the MSP to attempt to fix #618

---

bombastic/api/src/lib.rs
bombastic/api/src/server.rs
bombastic/index/src/packages/mod.rs
integration-tests/src/bom.rs
integration-tests/tests/bombastic.rs

* Add package index to bombastic API
* Add REST endpoint for package index
* Add integration test for package index
* Bump indexer memory limits in testing env to speed up package indexing
Issue #786
Issu3 #830

feat: add new package index to bombastic api

---

bombastic/api/src/server.rs
bombastic/index/src/packages/mod.rs
spog/api/src/app_state.rs
spog/api/src/config/default.yaml
spog/api/src/endpoints/package.rs
spog/ui/crates/components/src/packages/mod.rs
spog/ui/crates/components/src/packages/search.rs

issue https://github.com/trustification/trustification/issues/829

 add new endpoint for package of spog ui

---

Cargo.lock
Cargo.toml
deploy/compose/.env
spog/api/src/endpoints/sbom/vuln/analyze.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/api/src/service/guac.rs
spog/model/src/vuln.rs
spog/ui/src/pages/sbom_report/mod.rs

Also: Show the donut even if we have no information at all

Use the new GUAC API (by SBOM ID)

---

spog/api/src/endpoints/cve.rs

Implementation of `count_related_products` based on the existing query. It seems to me that performances are adequate for the initial dataset. We can optimize it later on.

feat: add count related products logic based on guac

---

Cargo.lock
Cargo.toml
collector/snyk/Cargo.toml
collector/snyk/src/lib.rs
event-bus/Cargo.toml
event-bus/src/lib.rs
event-bus/src/sqs.rs
storage/Cargo.toml
storage/src/lib.rs

Work towards fixing #839
Which gives us the following output now:
```
2023-11-20T15:45:33.761066Z  INFO trustification_storage: Update config to StorageConfig {
bucket: Some(
"vexination",
),
region: Some(
Custom {
region: "eu-central-1",
endpoint: "http://localhost:9000",
},
),
endpoint: Some(
"http://localhost:9000",
),
access_key: Some(
***,
),
secret_key: Some(
***,
),
validator: None,
}  
```

fix: don't log credentials

---

vexination/index/src/lib.rs
vexination/model/src/search.rs
vexination/testdata/rhsa-2023_1441.json

https://github.com/trustification/trustification/pull/853

add new field known not affected in vexination

---

Cargo.lock
deploy/k8s/chart/templates/spog/api/030-Deployment.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml
integration-tests/src/spog.rs
spog/api/Cargo.toml
spog/api/src/endpoints/analyze.rs
spog/api/src/lib.rs
spog/api/src/server.rs
spog/model/schema/config.json
spog/model/src/config.rs
spog/ui/src/pages/package/result/mod.rs

Fix up the following items:
* Allow disabling the package info tab
* Pass on the snyk token to CRDA (if present)

Some cleanups

---

deploy/konsole.tabs
spog/api/src/endpoints/package.rs
spog/api/src/error.rs
spog/model/src/package_info.rs
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/components/src/packages/mod.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/crates/components/src/spdx/mod.rs
spog/ui/crates/components/src/spdx/packages.rs
spog/ui/src/pages/cve/result/packages.rs
spog/ui/src/pages/sbom_report/details/packages.rs

Ensure that packages are properly linked in SPoG UI.
Also:
* remove unnecessary services from KDE konsole startup
* re-use pagination functionality

Link packages

---

Cargo.lock
Cargo.toml
deploy/compose/.env
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Fixes #890 and upgrades Guac image

fix: find_vulnerability should return only affected vex statements

---

spog/ui/src/pages/search.rs

The "SBOMs by dependencies" search is superseded by the "packages" search.

chore: drop dead code

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml

Closes: https://issues.redhat.com/browse/TC-756

fix(spogUi): don't accept invalid page numbers in text input

---

deploy/k8s/chart/templates/guac/collectsub/030-Deployment.yaml
deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml

Guac replicas configuration to enable configuration on Openshift

Guac replicas config

---

.tekton/trustification-service-push.yaml

Fix the deprecated configuration

Tekton timeouts

---

deploy/k8s/chart/templates/init-guac/020-Job.yaml
deploy/openshift/database-recreate-template.yaml
deploy/openshift/template.yaml

/hold for completion of https://github.com/trustification/trustification/pull/932

Restart guac

---

.github/workflows/ci.yaml

The CI should also lint the helm charts

ci: lint helm charts

---

spog/ui/src/pages/scanner/mod.rs

Whether the SBOM is SPDX or CycloneDX we need to validate the packages to make sure they are compliant with exhort requirements described at https://github.com/RHEcosystemAppEng/exhort#package-managers

[TC-777] - Validate purls before sending them to exhort

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml

https://issues.redhat.com/browse/TC-775

[TC-775] - Set fixed version of Patternfly-yew to "Fix Table header tooltips"

---

spog/ui/src/pages/cve/result/packages.rs

CVE:RelatedProducts:Dependencies table now has the columns: Type, Namespace, Name, Version, Path, Qualifiers, Dependency tree position.

CVE:RelatedProducts:Dependencies: Make package row consistent with other views showing more columns

---

deploy/openshift/template.yaml
deploy/openshift/values.yaml

Fix correct order of segment credentials

---

.github/matrix-users.yaml

Add [mrizzi](https://github.com/mrizzi) and its Matrix ID to users configuration.

Add mrizzi and its Matrix ID

---

.github/scripts/map-users/main.mjs
.github/workflows/rita-request-review.yaml

add some logging, trying to find out the reason for duplicate messages

ci: add a bit of logging, trying to find out the reason for duplicates

---

spog/ui/src/pages/package/result/mod.rs

[TC-803] - Package details: set namespace + name as title

---

bombastic/api/src/lib.rs

Not sure how to test this without deploying it to upstream staging

feat: implement liveness probe for bombastic api

---

.tekton/trustification-service-push.yaml
.tekton/trustification-tests-push.yaml

Tekton pipeline for release branch

---

.tekton/trustification-service-push.yaml
.tekton/trustification-tests-push.yaml

Disable Tekton pipeline on main branch

Disable tekton pipeline on main branch

---

deploy/k8s/chart/templates/guac/config/020-ConfigMap.yaml
deploy/openshift/template.yaml

Remove guac inmem configuration

---

deploy/k8s/chart/templates/init-dataset/030-CronJob.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Cherry pick of https://github.com/trustification/trustification/pull/1006 applied to stable to be promoted on stage

Dataset cronjob

---

deploy/openshift/template.yaml
deploy/openshift/values.yaml
spog/ui/Cargo.lock
spog/ui/crates/utils/Cargo.toml
spog/ui/crates/utils/src/analytics/mod.rs

Cherry pick of https://github.com/trustification/trustification/pull/973 applied to stable to be promoted on stage

[stable] Avoid sending null values in identity track events

---

spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/download.rs
spog/ui/crates/components/src/sbom/mod.rs

Cherry pick of https://github.com/trustification/trustification/pull/974 applied to stable to be promoted on stage

[stable] Enhance download tracking data

---

deploy/k8s/trustification-branding/files/spog-ui.yaml
spog/api/src/config/default.yaml

See https://issues.redhat.com/browse/TC-872

TC-872 spog-UI config

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/components/src/advisory/search.rs
spog/ui/crates/components/src/analytics.rs
spog/ui/crates/components/src/cve/search.rs
spog/ui/crates/components/src/lib.rs
spog/ui/crates/components/src/packages/search.rs
spog/ui/crates/components/src/sbom/search.rs
spog/ui/crates/components/src/search/dynamic.rs
spog/ui/crates/components/src/search/simple.rs
spog/ui/crates/utils/src/analytics/mod.rs

JIRA: https://issues.redhat.com/browse/TC-783

feat: add tracking events for filter controls

---

deploy/k8s/chart/templates/v11y/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/openshift/template.yaml

Setting deployment strategy to recreate

setting startegy

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/openshift/template.yaml

Cherry pick of
-  https://github.com/trustification/trustification/pull/1032
- https://github.com/trustification/trustification/pull/1037

[stable] setting strategy (#1032)

---

spog/api/src/app_state.rs
spog/api/src/endpoints/advisory.rs
spog/ui/crates/backend/src/advisory.rs
spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/advisory/search.rs
spog/ui/crates/components/src/lib.rs
spog/ui/crates/components/src/upload_file.rs
spog/ui/crates/navigation/src/lib.rs
spog/ui/src/console/mod.rs
spog/ui/src/pages/mod.rs
spog/ui/src/pages/vex_uploader/inspect.rs
spog/ui/src/pages/vex_uploader/mod.rs

Currently the buttons for uploading are called `Upload CSAF` and not `Upload Vex` as I understand `Vex` might be an internal way of calling CSAF files. Feel free to suggest to change the current naming of buttons

feat: Upload VEX

---

deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
deploy/openshift/template.yaml

I'll raise an issue to fix this argument issue

fix: move comment out of the args section

---

spog/model/schema/config.json
spog/model/src/config.rs
spog/ui/src/console/mod.rs
spog/ui/src/pages/uploader/mod.rs

- Make the Upload feat configurable
- Fix typos that refer to `Scan` in the Upload pages

feat: Upload Sbom|Vex enabled by config

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/collectorist/api/030-Deployment.yaml
deploy/k8s/chart/templates/exhort/api/030-Deployment.yaml
deploy/k8s/chart/templates/guac/collectsub/030-Deployment.yaml
deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
deploy/k8s/chart/templates/spog/api/030-Deployment.yaml
deploy/k8s/chart/templates/spog/ui/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Today most of the replica set is picked from REPLICAS value, this PR create a specific entry for each service pod

Specific replica setting per pod

---

deploy/k8s/chart/templates/bombastic/api/030-Deployment.yaml
deploy/k8s/chart/templates/bombastic/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/collectorist/api/030-Deployment.yaml
deploy/k8s/chart/templates/exhort/api/030-Deployment.yaml
deploy/k8s/chart/templates/guac/collectsub/030-Deployment.yaml
deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
deploy/k8s/chart/templates/spog/api/030-Deployment.yaml
deploy/k8s/chart/templates/spog/ui/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/api/030-Deployment.yaml
deploy/k8s/chart/templates/v11y/indexer/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/api/030-Deployment.yaml
deploy/k8s/chart/templates/vexination/indexer/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Cherry pick of https://github.com/trustification/trustification/pull/1040

[Stable] specific replica setting per pod (#1040)

---

spog/api/src/endpoints/analyze.rs
spog/ui/crates/components/src/sbom/report_viewer.rs

https://issues.redhat.com/projects/TC/issues/TC-930

[TC-930] - Print DA error details when report generation fails

---

vexination/walker/src/server.rs

Running inside tokio, to my understanding, that will just print a line on console, but keep going/failing.

chore: don't unwrap

---

admin/src/upload.rs
bombastic/api/src/server.rs
bombastic/index/src/packages/mod.rs
bombastic/index/src/sbom/mod.rs
collector/osv/src/lib.rs
collector/snyk/src/client/mod.rs
collector/snyk/src/lib.rs
collectorist/api/src/coordinator/collectors.rs
collectorist/api/src/coordinator/mod.rs
collectorist/api/src/db/mod.rs
common/src/tls.rs
index/src/s3dir.rs
rust-toolchain.toml
spog/api/src/endpoints/suggestion.rs
spog/api/src/service/guac.rs
spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/crates/components/src/theme.rs
spog/ui/src/pages/cve/result/packages.rs
v11y/index/src/lib.rs
vexination/index/src/lib.rs

Also fixed the warnings exposed by the newer rustc
This was motivated by an error only seen for apple targets: https://github.com/tkaitchuck/aHash/issues/195

feat: bump toolchain to latest stable, 1.75.0

---

.github/workflows/containers.yaml
.github/workflows/release.yaml
.github/workflows/snapshot.yaml
container_files/Containerfile.git

See: https://issues.redhat.com/browse/TC-952

Git image  

---

deploy/openshift/template.yaml
deploy/openshift/values.yaml

cherry pick from https://github.com/trustification/trustification/pull/1066

[Stable] Request api.trusted_content scope to get orgId

---

spog/ui/Cargo.lock
spog/ui/crates/utils/Cargo.toml
spog/ui/crates/utils/src/analytics/mod.rs

The organization id is a claim coming in the form:
```
"organization": {
"id": "123456"
},
```
It needs to be sent to segment.io for better tracking of data

feat: Send organization_id to segment.io

---

spog/ui/Cargo.lock
spog/ui/crates/utils/Cargo.toml
spog/ui/crates/utils/src/analytics/mod.rs

Cherry pick from https://github.com/trustification/trustification/pull/1070

[stable] feat: Send organization_id to segment.io

---

.github/workflows/ci.yaml
.github/workflows/integration.yaml
.github/workflows/unit.yaml
.gitignore
Cargo.lock
DEVELOPING.md
xtask/Cargo.toml
xtask/src/config.rs
xtask/src/errors.rs
xtask/src/main.rs
xtask/src/task/test.rs

Generate coverage reports for code covered by tests.
Issue: #466

xtask test: Support code coverage

---

spog/ui/src/pages/scanner/mod.rs

To keep a consistent look as in `spog/ui/src/pages/uploader/mod.rs`.

fix: Add missing space

---

spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/search/mod.rs

task: Rename tabs "products and containers" & "report". And add Tooltip to tab

---

spog/ui/src/pages/search.rs

Cherry pick from https://github.com/trustification/trustification/pull/1085

[stable] - Tab selection event data

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
bombastic/walker/Cargo.toml
bombastic/walker/src/scanner.rs
vexination/walker/Cargo.toml
vexination/walker/src/lib.rs
vexination/walker/src/server.rs

This reverts commit c883ec70c14a5bb506903b754003d7cbe6d9a0ea.

Revert "chore: support report in vexination walker"

---

spog/ui/crates/components/src/upload_file.rs
spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs

https://issues.redhat.com/browse/TC-1001

Make upload not-supported pkg errors become only warnings

---

spog/ui/src/console/mod.rs

https://issues.redhat.com/browse/TC-1009

Add tech preview banner

---

spog/ui/src/console/mod.rs

Origin https://github.com/trustification/trustification/pull/1136

[tech preview] Add tech preview banner

---

spog/ui/crates/components/src/common.rs
spog/ui/crates/components/src/content.rs
spog/ui/crates/components/src/cyclonedx/mod.rs
spog/ui/crates/components/src/spdx/mod.rs
spog/ui/crates/components/src/spdx/packages.rs
spog/ui/src/pages/package/result/package_info.rs

https://issues.redhat.com/browse/TC-1038
Reducing sizes of not only the the place that the ticket mentions but taking the opportunity to also reduce sizes in other card titles.

[TC-1038] - Reduce Card title sizes according to context

---

spog/ui/crates/components/src/common.rs
spog/ui/crates/components/src/content.rs
spog/ui/crates/components/src/cyclonedx/mod.rs
spog/ui/crates/components/src/spdx/mod.rs
spog/ui/crates/components/src/spdx/packages.rs
spog/ui/src/pages/package/result/package_info.rs

Origin https://github.com/trustification/trustification/pull/1144

[stable] [TC-1038] - Reduce Card title sizes according to context

---

spog/ui/src/pages/scanner/mod.rs

Origin https://github.com/trustification/trustification/pull/1148

[tech-preview] fix: go packages validation on Scan Sbom

---

spog/ui/src/pages/search/mod.rs
spog/ui/src/pages/search/search_input.rs

https://github.com/trustification/trustification/pull/1149

[tech preview] fix(ui): pressing search clear reloads the page

---

deploy/compose/.env
deploy/k8s/charts/trustification/values.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Promote changes from https://github.com/trustification/guac/pull/57

Bump guac v0.3.29

---

deploy/compose/.env
deploy/k8s/charts/trustification/values.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

Backport https://github.com/trustification/trustification/pull/1157

[release/1.0.z] Bump guac v0.3.29

---

vexination/index/src/lib.rs

This is required as we need the ID to look up the document at a later time. So we need to know the original, exact ID.

fix: store a raw/unaltered version of the ID

---

deploy/k8s/charts/trustification/templates/services/guac/graphql/030-Deployment.yaml

[release/1.0.z] fix: improve guac health check

---

README.md

respin build PR

---

spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-953

Add Privacy Statement for SBOM analysis

---

spog/ui/src/pages/sbom/mod.rs

origin: https://github.com/trustification/trustification/pull/1137

[release] Add Privacy Statement for SBOM analysis

---

.tekton/trustification-service-push.yaml
.tekton/trustification-tests-push.yaml

Increase tekton timeout, merge after the release

Increase tekton timeout

---

spog/api/src/endpoints/analyze.rs

In reponse to the latest comment  at https://issues.redhat.com/browse/TC-1067 `Finally I have also increased the default timeout in the Openshift routes to 3 minutes`.
We will also need to increase the timeout to 3 minutes as i verified our staging environment is still having 504 error

Increase DA timeout

---

spog/api/src/endpoints/analyze.rs

Origin https://github.com/trustification/trustification/pull/1213

[release] Increase default DA timeout on backend

---

spog/ui/crates/components/src/sbom/mod.rs

https://issues.redhat.com/browse/TC-1148

Sbom table: truncate name

---

spog/ui/crates/components/src/sbom/mod.rs

Orignated from https://github.com/trustification/trustification/pull/1236

[release/1.0.z] Sbom table: truncate name

---

spog/ui/crates/common/src/error/components.rs
spog/ui/crates/common/src/error/mod.rs
spog/ui/src/pages/sbom_report/mod.rs

Originated by https://github.com/trustification/trustification/pull/1221

[release/1.0.z] Enhance error component and set hardcoded message when guac fails

---

spog/ui/src/console/mod.rs

https://issues.redhat.com/browse/TC-1192

[TC-1192] - Remove Tech Preview banner

---

spog/ui/src/console/mod.rs

Originated from https://github.com/trustification/trustification/pull/1256

[release/1.0.z] - [TC-1192] - Remove Tech Preview banner

---

auth/src/client/inject.rs
bombastic/model/src/data.rs
container_files/Containerfile.services
infrastructure/src/app/http.rs
rust-toolchain.toml

Bump rust version (#1258)

---

docs/modules/admin/pages/cluster-install.adoc

docs: document the use of a custom trust anchor

---

spog/ui/src/pages/vex_uploader/mod.rs

Backport https://github.com/trustification/trustification/pull/1279

[release/1.0.z] Fix: CSAF/VEX 'Upload another' label

---

spog/model/src/config.rs
spog/ui/crates/common/src/config.rs
spog/ui/crates/components/src/advisory/search.rs
spog/ui/crates/components/src/cve/search.rs
spog/ui/crates/components/src/packages/search.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/crates/components/src/sbom/search.rs
spog/ui/crates/utils/src/analytics/component.rs
spog/ui/crates/utils/src/config/components.rs
spog/ui/crates/utils/src/config/mod.rs
spog/ui/src/about.rs
spog/ui/src/app.rs
spog/ui/src/console/mod.rs
spog/ui/src/pages/advisory/mod.rs
spog/ui/src/pages/cve/result/mod.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/package/result/mod.rs
spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/scanner/upload.rs
spog/ui/src/pages/uploader/mod.rs

https://issues.redhat.com/browse/TC-1213

[TC-1213] - Make the UI to use /api/v1/config

---

docs/modules/admin/pages/cluster-install.adoc

Backport https://github.com/trustification/trustification/pull/1290

Docs: add command to get URLs to accept in the browser

---

container_files/Containerfile.services

This reverts commit d688687fced932c23745f52c32a7bdd78a2d54eb.

Revert "Rootless runtime image"

---

spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/common/Cargo.toml
spog/ui/crates/components/Cargo.toml
spog/ui/crates/components/src/advisory/details/mod.rs
spog/ui/crates/components/src/advisory/details/product.rs
spog/ui/crates/components/src/advisory/details/remediation.rs
spog/ui/crates/components/src/advisory/mod.rs
spog/ui/crates/components/src/cve/mod.rs
spog/ui/crates/components/src/packages/mod.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/crates/components/src/spdx/mod.rs
spog/ui/crates/navigation/Cargo.toml
spog/ui/crates/utils/Cargo.toml
spog/ui/crates/utils/src/hints/mod.rs
spog/ui/src/pages/cve/result/advisories.rs
spog/ui/src/pages/cve/result/packages.rs
spog/ui/src/pages/cve/result/products.rs
spog/ui/src/pages/package/result/related_products.rs
spog/ui/src/pages/package/result/vulnerabilities.rs
spog/ui/src/pages/sbom_report/details/cve.rs
spog/ui/src/pages/sbom_report/details/packages.rs

Based on https://github.com/trustification/trustification/pull/1309 and https://github.com/trustification/trustification/pull/1310

[release/1.0.z] Update patternfly dependencies

---

spog/ui/src/console/mod.rs

https://issues.redhat.com/browse/TC-1237

[TC-1237] Remove Upload Routes when feature flag is disabled

---

spog/ui/src/console/mod.rs

Based on https://github.com/trustification/trustification/pull/1314

[release/1.0.z] [TC-1237] Remove Upload Routes when feature flag is disabled

---

spog/api/src/config/mod.rs
spog/ui/src/about.rs

Based on https://github.com/trustification/trustification/pull/1321

[release/1.0.z] [TC-1237] [TC-1248] ui: about model to use public config & expose features in the public api 

---

deploy/k8s/charts/trustification/values.yaml

Based on https://github.com/trustification/trustification/pull/1323

[release/1.0.z] chore: update Trustification image in helm chart

---

.tekton/trustification-product-1-0-z-pull-request.yaml
.tekton/trustification-product-1-0-z-push.yaml
.tekton/trustification-product-test-1-0-z-pull-request.yaml
.tekton/trustification-product-test-1-0-z-push.yaml

See https://github.com/redhat-appstudio/build-definitions/blob/main/task/deprecated-image-check/0.4/MIGRATION.md

Tekton deprecated-base-image-check migration

---

deploy/k8s/chart/templates/init-dataset/020-Job.yaml
deploy/openshift/dataset-template.yaml

Missing update of of https://github.com/trustification/trustification/pull/1251

dataset fix

---

deploy/k8s/chart/templates/init-dataset/020-Job.yaml
deploy/k8s/chart/templates/init-dataset/030-CronJob.yaml
deploy/openshift/dataset-template.yaml
deploy/openshift/template.yaml

fix walker path config

---

collector/osv/src/lib.rs
collector/snyk/src/lib.rs

Build GuacClient with provided reqwest::Client to manage TLS with ClientConfig

GuacClient to manage TLS

---

Cargo.lock
spog/api/Cargo.toml
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
v11y/index/Cargo.toml

Fixes https://issues.redhat.com/browse/TC-1495

Bump cve 0.3.0

---

spog/ui/src/pages/sbom/mod.rs

Re first requirement from https://issues.redhat.com/browse/TC-1177?focusedId=24856680&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24856680

TC-1177 - SBOM details page: 'Related advisories' tab renamed 'Related vulnerabilities'

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
collector/osv/Cargo.toml
collector/snyk/Cargo.toml
exhort/api/Cargo.toml
spog/api/Cargo.toml
spog/model/Cargo.toml
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/common/Cargo.toml
spog/ui/crates/components/Cargo.toml

TC-1177: bump packageurl and guac-rs versions

---

Cargo.lock
spog/api/Cargo.toml
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
v11y/index/Cargo.toml

Closes https://issues.redhat.com/browse/TC-1543

chore: update cve to 0.3.1, fixing some parsing issues

---

spog/api/src/endpoints/package.rs
spog/api/src/service/guac.rs

TC-1177 spog-api: retrieve CertifyVuln for package

---

Cargo.lock
v11y/testdata/CVE-2017-13052.json
v11y/testdata/CVE-2021-3601.json
v11y/testdata/CVE-2023-33201.json
v11y/walker/Cargo.toml
v11y/walker/src/lib.rs

TC-1177 v11y: missing score enhancement with OSV data

---

.tekton/trustification-service-pull-request.yaml
.tekton/trustification-service-push.yaml
.tekton/trustification-tests-pull-request.yaml
.tekton/trustification-tests-push.yaml
Cargo.lock
collector/osv/src/lib.rs
collector/snyk/src/lib.rs
deploy/k8s/chart/templates/init-dataset/020-Job.yaml
deploy/openshift/dataset-template.yaml
spog/api/Cargo.toml
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
v11y/index/Cargo.toml

update to 1.0.1

---

Cargo.lock
spog/api/Cargo.toml
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
v11y/index/Cargo.toml

[release/1.0.z] chore: update cve to 0.3.1, fixing some parsing issues

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
collector/osv/Cargo.toml
collector/osv/src/client/mod.rs
collector/osv/src/lib.rs
collector/osv/src/server.rs
collector/snyk/Cargo.toml
exhort/api/Cargo.toml
spog/api/Cargo.toml
spog/api/src/endpoints/package.rs
spog/api/src/service/guac.rs
spog/model/Cargo.toml
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/common/Cargo.toml
spog/ui/crates/components/Cargo.toml
spog/ui/src/pages/package/result/vulnerabilities.rs
spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/sbom_report/details/mod.rs
v11y/testdata/CVE-2017-13052.json
v11y/testdata/CVE-2021-3601.json
v11y/testdata/CVE-2023-33201.json
v11y/walker/Cargo.toml
v11y/walker/src/lib.rs

Backports:
- https://github.com/trustification/trustification/pull/1389
- https://github.com/trustification/trustification/pull/1390
- https://github.com/trustification/trustification/pull/1391
- https://github.com/trustification/trustification/pull/1400
- https://github.com/trustification/trustification/pull/1401
- https://github.com/trustification/trustification/pull/1402

[release/1.1.z] TC-1177 Backport PRs 

---

spog/api/src/endpoints/sbom/get.rs
spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-929
Backport:
- https://github.com/trustification/trustification/pull/1388

[release/1.1.z] TC-929 Set sbom name as download file

---

spog/ui/crates/components/src/advisory/details/remediation.rs
spog/ui/styles/main.scss

https://issues.redhat.com/browse/TC-1263
Backport:
- #1419

[release/1.1.z] TC-1263 Sex max with to Advisory/Vulnerability/Remediation content

---

spog/ui/src/pages/sbom_report/details/cve.rs

TC-1177 spog-ui Add advisory score

---

spog/ui/src/pages/sbom_report/details/cve.rs

Backport:
- https://github.com/trustification/trustification/pull/1432

[release/1.1.z] TC-1177 spog-ui Add advisory score

---

Cargo.lock
Cargo.toml
collectorist/api/src/coordinator/mod.rs
collectorist/api/src/lib.rs
collectorist/api/src/server/collector.rs
collectorist/api/src/state.rs

https://issues.redhat.com/browse/TC-1559

TC-1559 Collectorist API manages CollectSubClient with TLS

---

Cargo.lock
Cargo.toml
collectorist/api/src/coordinator/mod.rs
collectorist/api/src/lib.rs
collectorist/api/src/server/collector.rs
collectorist/api/src/state.rs

https://issues.redhat.com/browse/TC-1559
Backport:
- https://github.com/trustification/trustification/pull/1441

[release/1.1.z] TC-1559 Collectorist API manages CollectSubClient with TLS

---

spog/ui/crates/donut/patternfly-charts/package-lock.json

Backport:
- https://github.com/trustification/trustification/pull/1442
Bumps [braces](https://github.com/micromatch/braces) from 3.0.2 to 3.0.3.
- [Changelog](https://github.com/micromatch/braces/blob/master/CHANGELOG.md)
- [Commits](https://github.com/micromatch/braces/compare/3.0.2...3.0.3)
---
updated-dependencies:
- dependency-name: braces dependency-type: indirect ...

[release/1.1.z] build(deps): bump braces in /spog/ui/crates/donut/patternfly-charts

---

spog/api/src/endpoints/package.rs
spog/api/src/endpoints/sbom/mod.rs
spog/api/src/endpoints/sbom/vuln/mod.rs

https://issues.redhat.com/browse/TC-802

TC-802 Fetch vulnerabilities for packages

---

spog/api/src/endpoints/package.rs
spog/api/src/endpoints/sbom/mod.rs
spog/api/src/endpoints/sbom/vuln/mod.rs

https://issues.redhat.com/browse/TC-802
Backport:
- https://github.com/trustification/trustification/pull/1447

[release/1.1.z] TC-802 Fetch vulnerabilities for packages

---

collector/osv/src/server.rs

https://issues.redhat.com/browse/TC-1582
Backport
- https://github.com/trustification/trustification/pull/1463

[release/1.1.z] TC-1582 None CVE alias found management

---

Cargo.toml
integration-tests/src/bom.rs
integration-tests/src/lib.rs
integration-tests/src/provider.rs
integration-tests/src/runner.rs
integration-tests/src/spog.rs
integration-tests/src/ui.rs
integration-tests/src/vex.rs
integration-tests/tests/bombastic.rs
integration-tests/tests/spog.rs
integration-tests/tests/vexination.rs
spog/ui/Cargo.toml

Unignore and fix `integration-tests::spog::spog_dependencies` by updating expected values from responses.

Unignore and fix `integration-tests::spog::spog_dependencies`, refactor `integration-tests`

---

spog/ui/crates/components/src/advisory/mod.rs

https://issues.redhat.com/browse/TC-1599
Backport:
- https://github.com/trustification/trustification/pull/1478

[release/1.1.z] TC-1599: cover advisories without scores

---

spog/ui/src/pages/sbom_report/details/mod.rs

https://issues.redhat.com/browse/TC-1583
Backport:
- https://github.com/trustification/trustification/pull/1466

[release/1.1.z] TC-1583: show more/less options only when needed

---

spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-1578
Backport
- #1530

[release/1.1.z] TC-1578 Enhanced Vulnerabilities tab labels

---

bombastic/model/src/data.rs
bombastic/testdata/sbom-without-serialNumber.cyclonedx.json
storage/src/validator.rs

https://issues.redhat.com/browse/TC-1619
Backport
- #1531

[release/1.1.z] TC-1619 SBOM CycloneDX serialNumber validation

---

bombastic/model/src/data.rs

https://issues.redhat.com/browse/TC-1619

TC-1619 Improved error message

---

bombastic/model/src/data.rs

https://issues.redhat.com/browse/TC-1619
Backport:
- https://github.com/trustification/trustification/pull/1538

[release/1.1.z] TC-1619 Improved error message

---

deploy/openshift/template.yaml

new template with collectorist enabled

new template with collectorist enabled

---

deploy/k8s/chart/templates/collector/osv/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Osv collector and collectorist-api enabled

OSV collector and collectorist-api enabled

---

deploy/k8s/chart/templates/collector/osv/030-Deployment.yaml
deploy/openshift/parameters.yaml
deploy/openshift/template.yaml
deploy/openshift/values.yaml

Osv collector and collectorist-api enabled 1.0.z

Osv collector and collectorist-api enabled 1.0.z

---

.tekton/trustification-product-1-0-z-pull-request.yaml
.tekton/trustification-product-1-0-z-push.yaml
.tekton/trustification-product-test-1-0-z-pull-request.yaml
.tekton/trustification-product-test-1-0-z-push.yaml

Buildah migration https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md

buildah migration

---

.tekton/trustification-product-1-1-z-pull-request.yaml
.tekton/trustification-product-1-1-z-push.yaml
.tekton/trustification-product-test-1-1-z-pull-request.yaml
.tekton/trustification-product-test-1-1-z-push.yaml

migration buildah https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md

migration buildah

---

.tekton/trustification-service-pull-request.yaml
.tekton/trustification-service-push.yaml
.tekton/trustification-tests-pull-request.yaml
.tekton/trustification-tests-push.yaml

See here : https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md

buildah task migration

---

spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-1578
CycloneDX SBOM change just like the one done for SPDX SBOMs in #1530

TC-1578 CycloneDX enhanced Vulnerabilities tab labels

---

bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx.wrong-serialNumber.json

https://issues.redhat.com/browse/TC-1708

TC-1708 CycloneDX SBOM validation

---

bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx.wrong-serialNumber.json

https://issues.redhat.com/browse/TC-1708
Backport:
- https://github.com/trustification/trustification/pull/1661

[release/1.1.z] TC-1708 CycloneDX SBOM validation

---

.github/workflows/integration.yaml

See: 
- https://docs.docker.com/compose/migrate/ 
- https://github.com/orgs/community/discussions/116610

[stable] fix docker compose command

---

.github/workflows/integration.yaml

See: 
- https://docs.docker.com/compose/migrate/ 
- https://github.com/orgs/community/discussions/116610

[1.1.z] Fix compose GH 11z

---

.github/workflows/integration.yaml

See: 
- https://docs.docker.com/compose/migrate/ 
- https://github.com/orgs/community/discussions/116610

[1.0.z] fix docker compose command

---

.github/workflows/integration.yaml

See:
-     https://docs.docker.com/compose/migrate/
-     https://github.com/orgs/community/discussions/116610

[multi] fix docker compose command

---

collector/osv/src/client/mod.rs
collector/osv/src/client/schema.rs

https://issues.redhat.com/browse/TC-1714
Backport:
- https://github.com/trustification/trustification/pull/1693

[release/1.2.z] TC-1714 Enhanced Ecosystem enum

---

bombastic/api/src/server.rs
bombastic/index/src/sbom/mod.rs
bombastic/model/src/search.rs
index/src/lib.rs
spog/api/src/app_state.rs
spog/api/src/endpoints/dashboard.rs
spog/api/src/endpoints/mod.rs
spog/api/src/server.rs
spog/api/src/service/v11y.rs
spog/model/src/dashboard.rs
spog/model/src/lib.rs
v11y/api/src/server/mod.rs
v11y/api/src/server/search.rs
v11y/client/src/lib.rs
v11y/index/src/lib.rs
v11y/model/src/search.rs
vexination/api/src/server.rs
vexination/index/src/lib.rs
vexination/model/src/search.rs

https://issues.redhat.com/browse/TC-1668

[TC-1668] - Dashboard - Status panel - back end

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1640

TC-1640: upgrade npm async dependency

---

event-bus/src/kafka.rs

This is an attempt to "safe consumer commit" let's say.
Based on this small PoC findings detailed here https://github.com/trustification/trustification/issues/1024

fix: check events existence before commit

---

bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx.newline.json

https://issues.redhat.com/browse/TC-1730
Backports
- #1700

[release/1.1.z] TC-1730 fix: allow control characters in CyclonDX JSON fields

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1640
Backport:
- #1701

[release/1.1.z] TC-1640: upgrade npm async dependency

---

bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx.newline.json

https://issues.redhat.com/browse/TC-1730
Backports
- #1700

[release/1.2.z] fix: allow control characters in CyclonDX JSON fields

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1640
Backport:
- #1701

[release/1.2.z] TC-1640: upgrade npm async dependency

---

collector/osv/src/client/mod.rs

https://issues.redhat.com/browse/TC-1714
Porting of https://github.com/trustification/trustification/pull/1715

TC-1714 Found new vulnerabilties for testing Ubuntu ecosystem

---

bombastic/api/src/server.rs
bombastic/index/src/sbom/mod.rs
bombastic/model/src/search.rs
index/src/lib.rs
spog/api/src/app_state.rs
spog/api/src/endpoints/dashboard.rs
spog/api/src/endpoints/mod.rs
spog/api/src/server.rs
spog/api/src/service/v11y.rs
spog/model/src/dashboard.rs
spog/model/src/lib.rs
v11y/api/src/server/mod.rs
v11y/api/src/server/search.rs
v11y/client/src/lib.rs
v11y/index/src/lib.rs
v11y/model/src/search.rs
vexination/api/src/server.rs
vexination/index/src/lib.rs
vexination/model/src/search.rs

https://issues.redhat.com/browse/TC-1668
Backport:
- https://github.com/trustification/trustification/pull/1576

[release/1.2.z][TC-1668] - Dashboard - Status panel - back end (#1576)

---

spog/api/src/endpoints/sbom/mod.rs
spog/api/src/endpoints/sbom/search.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/model/src/dashboard.rs

https://issues.redhat.com/browse/TC-1666
Backporting https://github.com/trustification/trustification/pull/1550

[release/1.2.z] [TC-1666] - Ten Latest Sboms with vulnerabilities summary backend

---

spog/ui/src/about.rs
spog/ui/styles/main.scss

https://issues.redhat.com/browse/TC-1732

[TC-1732] - change about modal's content

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
bombastic/index/src/packages/mod.rs
bombastic/index/src/sbom/mod.rs
bombastic/model/Cargo.toml
bombastic/model/src/data.rs
bombastic/walker/Cargo.toml
bombastic/walker/src/processing.rs
bombastic/walker/src/report.rs
common/walker/Cargo.toml
integration-tests/src/lib.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/ui/Cargo.lock
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/components/Cargo.toml
vexination/walker/Cargo.toml
vexination/walker/src/report.rs

I made a PoC, updating the cyclonedx dependency to a newer version. That includes an update of the walker stuff too.
I haven't tested it though. I could use some help with that. But let's first see what the CI thinks about it.

feat: support cyclonedx 1.5

---

bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx-1.5.json

https://issues.redhat.com/browse/TC-1750

TC-1750 CycloneDx 1.5 test

---

spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs

https://issues.redhat.com/browse/TC-1750

TC-1750 spog-ui

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
bombastic/index/src/packages/mod.rs
bombastic/index/src/sbom/mod.rs
bombastic/model/Cargo.toml
bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx-1.5.json
bombastic/walker/Cargo.toml
bombastic/walker/src/processing.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/components/Cargo.toml
spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs
vexination/walker/Cargo.toml

https://issues.redhat.com/browse/TC-1750
Backports:
- https://github.com/trustification/trustification/pull/1721
- https://github.com/trustification/trustification/pull/1725
- https://github.com/trustification/trustification/pull/1727

[release/1.1.z] TC-1750 Support for CycloneDx 1.5

---

Cargo.lock
Cargo.toml
bombastic/index/Cargo.toml
bombastic/index/src/packages/mod.rs
bombastic/index/src/sbom/mod.rs
bombastic/model/Cargo.toml
bombastic/model/src/data.rs
bombastic/testdata/syft.cyclonedx-1.5.json
bombastic/walker/Cargo.toml
bombastic/walker/src/processing.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/ui/Cargo.toml
spog/ui/crates/backend/Cargo.toml
spog/ui/crates/components/Cargo.toml
spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs
vexination/walker/Cargo.toml

https://issues.redhat.com/browse/TC-1750
Backport:
- https://github.com/trustification/trustification/pull/1729

[release/1.2.z] TC-1750 Support for CycloneDx 1.5

---

v11y/testdata/CVE-2023-50164.json
v11y/walker/src/lib.rs

https://issues.redhat.com/browse/TC-1775

TC-1755 Add management for metrics array with no CVSS entry

---

v11y/testdata/CVE-2023-50164.json
v11y/walker/src/lib.rs

https://issues.redhat.com/browse/TC-1775
Backport
- #1731

[release/1.2.z] TC-1755 Add management for metrics array with no CVSS entry

---

Cargo.lock
auth/src/client/error.rs
deploy/compose/.env
deploy/compose/compose-trustification.yaml
deploy/k8s/charts/trustification-infrastructure/Chart.yaml
deploy/k8s/charts/trustification/templates/helpers/_preferences.tpl
deploy/k8s/charts/trustification/templates/services/spog/api/010-PersistentVolumeClaim.yaml
deploy/k8s/charts/trustification/templates/services/spog/api/030-Deployment.yaml
deploy/k8s/charts/trustification/values.schema.json
deploy/k8s/charts/trustification/values.schema.yaml
deploy/k8s/charts/trustification/values.yaml
integration-tests/src/spog.rs
spog/api/Cargo.toml
spog/api/src/app_state.rs
spog/api/src/db/mod.rs
spog/api/src/endpoints/dashboard.rs
spog/api/src/lib.rs
spog/api/src/server.rs
spog/model/src/dashboard.rs
spog/ui/Cargo.lock

https://issues.redhat.com/browse/TC-1672
Backport
https://github.com/trustification/trustification/pull/1695
The Doughnut charts that show the SBOM vulnerabilities for the 4 SBOMs the user is tracking is the first feature that requires the application to store user preferences.

[release/1.2.z][TC-1672]  User Preferences back end

---

spog/ui/crates/backend/src/dashboard.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/sbom_report/mod.rs
spog/ui/styles/main.scss

https://issues.redhat.com/browse/TC-1673
Based on top of https://github.com/trustification/trustification/pull/1659
Current status:
- We can search and select any SBOM
- We are still not able to save the user preferences on the backend, waiting for https://github.com/trustification/trustification/pull/1695 to be completed
https://github.com/user-attachments/assets/6711add3-b9ef-49a1-8840-47de3c833280

[TC-1673] - Dashboard - User Preferences - front end - Donut Charts

---

spog/ui/crates/backend/src/dashboard.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/sbom_report/mod.rs
spog/ui/styles/main.scss

https://issues.redhat.com/browse/TC-1673
Backport of https://github.com/trustification/trustification/pull/1720

[release/1.2.z][TC-1673] - Dashboard - User Preferences - front end - Donut Charts

---

spog/ui/src/pages/index.rs

Align fields as per requested at https://issues.redhat.com/browse/TC-1669?focusedId=25515839&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25515839

[TC-1669]-Dashboard - Status panel - front end - fix field aligments

---

spog/ui/src/pages/index.rs

https://issues.redhat.com/browse/TC-1669
backport from https://github.com/trustification/trustification/pull/1743

[release/1.2.z][TC-1669]-Dashboard - Status panel - front end - fix field aligments

---

spog/api/src/endpoints/sbom/search.rs

https://issues.redhat.com/browse/TC-1666
Backport of https://github.com/trustification/trustification/pull/1745

[release/1.2.z][TC-1666] - Dashboard - Bar chart back end - change ordering of 10 latest sboms dashboard retrieval

---

spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs

https://issues.redhat.com/browse/TC-1778

[TC-1778]-SPDX 2.3 Support-add supported formats to upload/scan ui page

---

spog/ui/src/pages/scanner/mod.rs
spog/ui/src/pages/uploader/mod.rs

Backport of https://github.com/trustification/trustification/pull/1756
https://issues.redhat.com/browse/TC-1778

[release/1.2.z][TC-1778]-SPDX 2.3 Support-add supported formats to upload/scan ui page

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1770

[TC-1770]-Upgrade body-parser dependency

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

Backport of https://github.com/trustification/trustification/pull/1754
https://issues.redhat.com/browse/TC-1770

[release/1.2.z][TC-1770]-Upgrade body-parser dependency

---

Cargo.lock
Cargo.toml
collector/osv/src/server.rs
collector/snyk/src/server.rs
deploy/compose/.env
deploy/k8s/legacy/values-crc.yaml
deploy/k8s/legacy/values-minikube.yaml
deploy/k8s/legacy/values-openshift-blueprint.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

https://issues.redhat.com/browse/TC-1794
Backports:
- https://github.com/trustification/trustification/pull/1749

[release/1.2.z] TC-1794 Update guac-rs v0.7.2

---

spog/ui/src/about.rs

https://issues.redhat.com/browse/TC-1732

[TC-1732] - ui: Change hardcoded version in the about modal

---

spog/ui/src/about.rs

Backport of:
- https://github.com/trustification/trustification/pull/1702
- https://github.com/trustification/trustification/pull/1763
https://issues.redhat.com/browse/TC-1732

[release/1.2.z][TC-1732] - change about modal's content

---

deploy/compose/.env
deploy/k8s/legacy/values-crc.yaml
deploy/k8s/legacy/values-minikube.yaml
deploy/k8s/legacy/values-openshift-blueprint.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

https://issues.redhat.com/browse/TC-1626
Backport:
- https://github.com/trustification/trustification/pull/1767

[release/1.2.z] TC-1626 Bump Guac v0.7.2-RC8

---

deploy/compose/.env
deploy/k8s/legacy/values-crc.yaml
deploy/k8s/legacy/values-minikube.yaml
deploy/k8s/legacy/values-openshift-blueprint.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

https://issues.redhat.com/browse/TC-1814
Backport:
- https://github.com/trustification/trustification/pull/1773

[release/1.2.z] TC-1814 Guac image update

---

spog/ui/crates/components/src/spdx/mod.rs

https://issues.redhat.com/browse/TC-1815
Backports:
- https://github.com/trustification/trustification/pull/1776

[release/1.2.z] TC-1815 SBOM details page: enhance 'Info' tab formatting

---

.tekton/trustification-product-1-2-z-pull-request.yaml
.tekton/trustification-product-1-2-z-push.yaml

Migrations from the tekton updates

Changes from the pipeline updates

---

spog/ui/src/pages/index.rs
spog/ui/src/pages/search/search_input.rs

Backport of https://github.com/trustification/trustification/pull/1836
https://issues.redhat.com/browse/TC-1839

[release/1.2.z][TC-1839] - Change TPA home page

---

spog/api/src/endpoints/sbom/search.rs

https://issues.redhat.com/browse/TC-1819
https://issues.redhat.com/browse/TC-1823

TC-1819: reverse search order to find last 10 sboms ingested

---

spog/ui/src/pages/index.rs

https://issues.redhat.com/browse/TC-1822
Removing `You can also select up to 4 SBOMs to watch, by default you will see the last 4 SBOMs you have uploaded.` as agreed in the ticket

[TC-1822]: Update Dashboard-BarChart header text

---

spog/ui/src/pages/index.rs

https://issues.redhat.com/browse/TC-1822
Backport of https://github.com/trustification/trustification/pull/1842

[release/1.2.z][TC-1822]: Update Dashboard-BarChart header text (#1842)

---

bombastic/index/src/packages/mod.rs
bombastic/testdata/openssl-3.0.7-18.el9_2.spdx.json

https://issues.redhat.com/browse/TC-1757
Backport:
- #1892

[release/1.2.z] TC-1757 SPDX: manage multiple PURLs per package

---

deploy/compose/.env
deploy/k8s/legacy/values-crc.yaml
deploy/k8s/legacy/values-minikube.yaml
deploy/k8s/legacy/values-openshift-blueprint.yaml
deploy/trustification.dev/dev.yaml
deploy/trustification.dev/prod.yaml
deploy/trustification.dev/staging.yaml

https://issues.redhat.com/browse/TC-1847
Backport:
- https://github.com/trustification/trustification/pull/1917

[release/1.2.z] TC-1847 Guac image update

---

bombastic/index/src/sbom/mod.rs
bombastic/testdata/my-sbom.json
spog/ui/crates/components/src/cyclonedx/mod.rs
spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-1842
Backports:
- https://github.com/trustification/trustification/pull/1923

[release/1.2.z] TC-1842 CycloneDX CPE management

---

bombastic/model/src/data.rs
bombastic/testdata/cdx-1.5-valid-license-id.json

https://issues.redhat.com/browse/TC-1841

TC-1841 cyclonedx 1.5 validation avoiding 1.3 default call

---

bombastic/model/src/data.rs
bombastic/testdata/cdx-1.5-valid-license-id.json

https://issues.redhat.com/browse/TC-1841
Backport:
- https://github.com/trustification/trustification/pull/1955

[release/1.2.z] TC-1841 cyclonedx 1.5 validation avoiding 1.3 default call

---

v11y/walker/src/lib.rs

https://issues.redhat.com/browse/TC-1865
Backports:
- https://github.com/trustification/trustification/pull/1987
- https://github.com/trustification/trustification/pull/2056

[release/1.2.z] TC-1865 Fix multiple prefixes management

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1789

[TC-1789]-task: upgrade serialize-javascript to 6.0.2

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

backport https://github.com/trustification/trustification/pull/2071
https://issues.redhat.com/browse/TC-1789

[release/1.2.z][TC-1789]-task: upgrade serialize-javascript to 6.0.2

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

https://issues.redhat.com/browse/TC-1824
Depends on https://github.com/trustification/trustification/pull/2071

[TC-1824] - upgrade http-proxy-middleware

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

Backport of https://github.com/trustification/trustification/pull/2073
https://issues.redhat.com/browse/TC-1824

[release/1.2.z][TC-1824] - upgrade http-proxy-middleware 

---

spog/ui/crates/donut/patternfly-charts/package-lock.json
spog/ui/crates/donut/patternfly-charts/package.json

Backport of https://github.com/trustification/trustification/pull/2074
https://issues.redhat.com/browse/TC-1870

[release/1.2.z][TC-1870]-upgrade cross-spawn (#2074)

---

spog/ui/src/about.rs

Set Version to "main". To clearly differentiate in which version we are working on

task: update "About" version

---

spog/ui/src/about.rs
version/src/lib.rs

Backport of https://github.com/trustification/trustification/pull/2096
https://issues.redhat.com/browse/TC-1892

[release/1.2.z][TC-1892] fix: hardcoded provided version on API 

---

spog/api/src/endpoints/sbom/search.rs
spog/api/src/endpoints/sbom/vuln/analyze.rs
spog/api/src/endpoints/sbom/vuln/mod.rs
spog/ui/crates/backend/src/sbom.rs
spog/ui/src/pages/index.rs
spog/ui/src/pages/sbom_report/mod.rs

https://issues.redhat.com/browse/TC-1970
Backports:
- https://github.com/trustification/trustification/pull/2091

[release/1.2.z] TC-1970 Dashboard: enhance vulnerabilities retrieval

---

collector/osv/src/client/schema.rs
collector/osv/src/server.rs

https://issues.redhat.com/browse/TC-2022
Backport:
- https://github.com/trustification/trustification/pull/2100

[release/1.3.z] TC-2022 Fix OSV CVSS_V4 severity type ingestion (#2100)

---

collector/osv/src/client/schema.rs
collector/osv/src/server.rs

https://issues.redhat.com/browse/TC-2022
Backport:
- https://github.com/trustification/trustification/pull/2100

[release/1.2.z] TC-2022 Fix OSV CVSS_V4 severity type ingestion

---

Cargo.lock
spog/api/Cargo.toml
spog/api/src/endpoints/license.rs
spog/api/src/endpoints/mod.rs
spog/api/src/lib.rs
spog/api/src/license/license_exporter.rs
spog/api/src/license/license_scanner.rs
spog/api/src/license/mod.rs
spog/api/src/server.rs
spog/api/src/utils/mod.rs
spog/test-data/application.cdx.json
spog/test-data/my-sbom.json

https://issues.redhat.com/browse/TC-1886
Backport of https://github.com/trustification/trustification/pull/2040

[release/1.3.z][TC-1886] - sbom license scanner backend

---

spog/ui/crates/components/src/download.rs
spog/ui/crates/components/src/sbom/mod.rs
spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-1886
Backport of https://github.com/trustification/trustification/pull/2064

[release/1.3.z][TC-1886]: sbom license scanner frontend

---

spog/ui/src/pages/sbom/mod.rs
spog/ui/src/pages/scanner/mod.rs

backport of https://github.com/trustification/trustification/pull/2094
https://issues.redhat.com/browse/TC-1978

[release/1.3.z][TC-1978] task: remove dependency analytics from UI (#2094)

---

v11y/index/src/lib.rs
v11y/testdata/CVE-2023-6260.json

https://issues.redhat.com/browse/TC-1710

[TC-1710] Inconsistent visuals when a CVE has multiple CVSS scores

---

spog/ui/src/pages/sbom/mod.rs

https://issues.redhat.com/browse/TC-2182
Backport:
- https://github.com/trustification/trustification/pull/2155

[release/1.3.z] TC-2182 Avoid ReportViewwer fetching data (#2155)

---

spog/api/src/license/license_exporter.rs
spog/api/src/license/license_scanner.rs

- https://issues.redhat.com/browse/TC-2150
- https://issues.redhat.com/browse/TC-2160
- https://issues.redhat.com/browse/TC-2187
- https://issues.redhat.com/browse/TC-2212
- https://issues.redhat.com/browse/TC-2213
Backport:
- https://github.com/trustification/trustification/pull/2157

TC-2150 TC-2160 TC-2187 TC-2212 TC-2213 License export issues

---

spog/api/src/endpoints/sbom/vuln/mod.rs

https://issues.redhat.com/browse/TC-2103

TC-2103 spog-api: improve v11y search query and result management

---

spog/api/src/endpoints/sbom/vuln/mod.rs

https://issues.redhat.com/browse/TC-2103
Backport:
- https://github.com/trustification/trustification/pull/2169

[release/1.3.z] TC-2103 spog-api: improve v11y search query and result management

---

Cargo.lock
Cargo.toml

https://issues.redhat.com/browse/TC-2279

TC-2279 Bump guac 0.7.2-1
