trustification/trustification

- vexination/index/src/search.rs
@ctron Temporary until we've figured out what to do with the expression parsing.
> fix: remove cvss from default fields for the moment

- bombastic/index/src/lib.rs
This fixes a `thread 'main' panicked at 'Field already exists in schema purl'` error.
> Fixed 'cpe' index field name

- Cargo.lock
- DEVELOPING.md
- bombastic/api/Cargo.toml
- bombastic/api/src/server.rs
- storage/src/lib.rs
- vexination/api/src/server.rs
We create a general purpose `Error` enum for the bombastic server, which enables us to exploit `?` in the handlers to simplify their logic.
> refactor: consolidate handlers and use response-from-error feature

- Cargo.lock
- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- index/src/lib.rs
- spog/api/src/advisory.rs
- spog/api/src/sbom.rs
- spog/api/src/vulnerability.rs
- spog/model/Cargo.toml
- spog/model/src/search.rs
- spog/ui/Cargo.lock
- spog/ui/src/backend/vuln.rs
- spog/ui/src/components/advisory.rs
- spog/ui/src/components/common.rs
- spog/ui/src/components/package.rs
- spog/ui/src/components/vulnerability.rs
- spog/ui/src/pages/advisory/mod.rs
- spog/ui/src/pages/package/mod.rs
- spog/ui/src/pages/vulnerability/mod.rs
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
* add separate type for advisory summary to speed up fetching
* fetch CSAF document on-demand when rendering details
* generate snippets of description to highlight parts that matches a query
* add more fields to index and refactor how field data is retrieved
> feat: add advisory summary to use in frontend

- bombastic/api/src/server.rs
- storage/src/lib.rs
- vexination/api/src/server.rs
- vexination/index/src/lib.rs
- vexination/walker/src/server.rs
Removes some of the hard-coded assumptions (or makes them explicit) in the storage api.
> feat: refactor to facilitate non-json SBOM's

- bombastic/index/src/lib.rs
- bombastic/index/src/search.rs
* Remove multiple fields from default search to prevent misleading results
* Only search on package name and description by default
> feat: reduce default set of searched fields

- Cargo.lock
- bombastic/api/src/server.rs
- storage/Cargo.toml
- storage/src/lib.rs
Fixes #161
This required [a fix in the rust-s3 crate](https://github.com/durch/rust-s3/pull/353) so we're now depending on a branch of a fork of that repo.
The fork's API differs slightly from the version we were previously using: we can now report the size of the upload instead of just the status code.
And while I was at it, I removed a confusing debug println that should clean up our server log a bit.
> fix: metadata can now be attached to large, multipart SBOM's

- bombastic/api/src/server.rs
- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- index/src/lib.rs
- spog/api/src/advisory.rs
- spog/api/src/sbom.rs
- vexination/api/src/server.rs
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
Provide a JSON tantivy explanation if a flag enabling it is passed during
the search. This flag can set as a query parameter in bombastic and
vexination.
> feat: add option to explain why a document matched

- bombastic/index/src/lib.rs
- index/src/lib.rs
- vexination/index/src/lib.rs
This changes a query for a specific date to a range query matching the
entire day, rather than at millisecond granularity. For finer
granularity, specifying a restricted range will still work.
Fixes #176
> fix: change date queries to match on day instead of millisecond

- integration-tests/tests/bombastic.rs
I don't love this. I'd like to break each test out into its own fn, but I don't like that I only have one `#[test]` fn that calls all the rest in the correct order. 
I'd like for each test to be annotated with `#[test]` so we can see our test counts increase over time. :smile:
> refactor: integs

- Cargo.lock
- index/Cargo.toml
- index/src/lib.rs
* On insertion, delete documents with a matching unique identifier
* Add unit tests for trustification-index covering duplicates and index
operations.
Fixes #201
> fix: prevent duplicates in index

- spog/ui/src/components/advisory.rs
- spog/ui/src/components/common.rs
- spog/ui/src/components/mod.rs
- spog/ui/src/components/package.rs
- spog/ui/src/components/simple_pagination.rs
- spog/ui/src/components/table_wrapper.rs
- spog/ui/src/components/vulnerability.rs
- spog/ui/src/console.rs
- spog/ui/src/hooks/use_pagination_state.rs
- spog/ui/src/pages/advisory/mod.rs
- spog/ui/src/pages/catalog/mod.rs
- spog/ui/src/pages/package/mod.rs
[Screencast from 2023-06-23 11-37-40.webm](https://github.com/trustification/trustification/assets/2582866/40c685e8-ce83-47b9-9c3c-2b740e97caff)
[Screencast from 2023-06-23 11-42-09.webm](https://github.com/trustification/trustification/assets/2582866/e6eb709d-578d-456d-acdb-b72d97d896c3)
> UI: pollish visual styles of components

- bombastic/index/src/lib.rs
- index/src/lib.rs
A positive term is required for a not query to have some results to act
match. Adding a AllQuery term in union with the not term ensures the not
term has candidate hits to match against.
Fixes #215
> fix: add positive term for not queries

- Cargo.lock
- bombastic/api/Cargo.toml
- bombastic/api/src/lib.rs
- integration-tests/src/lib.rs
- vexination/api/Cargo.toml
- vexination/api/src/lib.rs
This is a temporary change that will be replaced by proper
authentication and authorization, but is useful in order to keep the
public instances of trustification protected.
> feat: add basic authentication support for write APIs

- integration-tests/src/lib.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/vexination.rs
We still provide `run_test`, but I think that'll evolve to `with_spog`
> feat: enable test harness to provide either bombastic or vexination

- spog/ui/src/components/spdx/mod.rs
- spog/ui/src/components/spdx/packages.rs
Quarkus packages has duplicate information, as have some packages with duplicate versions.
We try to de-duplicate in a reasonable fashion. Duplicate SPDX entries are simply hidden, while versions will be grouped when PackageURLs are used.
Also:
* Don't show empty tooltips
> Try deduplicating information

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
- api/src/lib.rs
- api/src/search.rs
- bombastic/api/Cargo.toml
- bombastic/api/src/server.rs
- bombastic/index/Cargo.toml
- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- index/Cargo.toml
- index/src/lib.rs
- index/src/metadata.rs
- spog/api/Cargo.toml
- spog/api/src/advisory.rs
- spog/api/src/sbom.rs
- spog/api/src/server.rs
- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/src/backend/mod.rs
- spog/ui/src/backend/pkg.rs
- spog/ui/src/backend/search.rs
- spog/ui/src/backend/vuln.rs
- spog/ui/src/components/advisory/search.rs
- spog/ui/src/components/sbom/mod.rs
- vexination/api/Cargo.toml
- vexination/api/src/server.rs
- vexination/index/Cargo.toml
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
When searching the index it is not always clear to me "why" a document matched or didn't. I also want to understand what additional information is stored in the index in order to understand what I can search for.
This change adds the ability to request the raw index document content alongside the actual search document as returned on the API.
For example:
```
http -v localhost:8082/api/v1/sbom/search q=="ubi" metadata==true
```
Results in: https://gist.github.com/ctron/6978595544d7b15fd9ceb76cf3ba4804
By default no metadata is returned. When the frontend is compiled in debug mode, it is requested by default.
Also: `explain` seems to be broken at the moment #283
> Allow returning index document when searching

- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- vexination/model/src/search.rs
We did re-iterate over the search model for vulnerabilities, but it looks like this hasn't happened for packages.
This is a proposal to remove unnecessary annotations, and use scope or default for cases where primary is used, or use &str instead.
> fix: clean up the search model for package as well

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/src/components/advisory/mod.rs
Quarkus SBOMs are using an invalid product ID. This get flagged now:
> fix: show alert when product id is invalid

- spog/api/src/config/default.yaml
- spog/api/src/config/mod.rs
- spog/api/src/config/schema.yaml
- spog/api/src/lib.rs
- spog/model/src/config.rs
- spog/ui/src/pages/index.rs
This allows to override the content section of the landing page through the SPoG UI config.
The idea is to provide a reasonable default, allowing to override the content in a custom deployment without the need to patch the actual source code.
> feat: allow overriding the landing page content

- Cargo.lock
- auth/src/authenticator/mod.rs
- integration-tests/Cargo.toml
- integration-tests/src/bom.rs
- integration-tests/src/vex.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/vexination.rs
- spog/api/src/sbom.rs
- chore: make test upload fn available to all tests
- fix: query associated advisories using cpe OR purl
- fix: cargo fmt
> correlate advisories

- spog/ui/src/app.rs
Backdrop content might require the access token too. So the backdrop viewer needs to be wrapped by the oauth2 context.
closes #329
> fix: wrap the backdrop viewer with the oauth2 context

- deploy/compose/.env
- deploy/compose/compose-trustification.yaml
- deploy/compose/compose-walkers.yaml
- deploy/compose/compose.yaml
- infrastructure/Cargo.toml
- infrastructure/src/infra.rs
Also: add a sigterm handler to all processes using `Infrastructure` to enable shutdown without the need for `SIGKILL`.
> Improve the compose deployment

- DEVELOPING.md
- auth/src/authenticator/config.rs
- auth/src/authenticator/mod.rs
- auth/src/authorizer/mod.rs
- auth/src/lib.rs
- bombastic/api/src/lib.rs
- bombastic/api/src/server.rs
- infrastructure/src/app.rs
- spog/api/src/server.rs
- vexination/api/src/lib.rs
- vexination/api/src/server.rs
Add an authorizer to APIs that controls if a request should be authorized based on user details.  When --devmode is enabled, authorization is disabled (authentication still enabled), otherwise it is always enabled.
> Allow disabling authorization

- README.md
This commit removes the README.md paths from the links to the reservoir and spog READMEs as they don't exist.
> Fix link to reservoir and spog READMEs

- Cargo.lock
- bombastic/api/src/lib.rs
- bombastic/api/src/server.rs
- bombastic/index/src/lib.rs
- bombastic/indexer/src/lib.rs
- index/Cargo.toml
- index/src/lib.rs
- index/src/s3dir.rs
- indexer/src/lib.rs
- integration-tests/src/lib.rs
- storage/src/lib.rs
- vexination/api/src/lib.rs
- vexination/api/src/server.rs
- vexination/index/src/lib.rs
- vexination/indexer/src/lib.rs
* Add a runtime config option to enable s3 directory backed index.
* Implement tantivy directory trait based on s3 storage to bypass the local filesystem and syncing.
Issue #333
> feat: support using s3 directly as index backing store

- .cargo/config.toml
- .github/workflows/integration.yaml
- Cargo.lock
- bombastic/testdata/ubi9-sbom.json
- indexer/src/lib.rs
- integration-tests/Cargo.toml
- integration-tests/src/bom.rs
- integration-tests/src/lib.rs
- integration-tests/src/provider.rs
- integration-tests/src/vex.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/vexination.rs
Fixes #363 
Includes a new `wait_for_event` helper and demonstrates how unique id's can help mitigate test confusion stemming from stale data persisting in local stores (minio/kafka) across test runs.
> Enable integs to assert certain events occur

- README.md
This commit updates the instructions for starting the containers locally and specifically that the keycloak container needs to be started first and fully initialized before the other containers are started.
The motivation for this change is that the containers that depend on keyclaok will fail because the
http://keycloak:8080/realms/chicken/.well-known/openid-configuration endpoint will not be available that the time they start.
At least this is the behavior that I seeing on Linux and I think it would help others starting up the project to have this information in the README as a possible workaround.
Refs: https://github.com/danbev/learning-crypto/blob/main/notes/seedwing/podman-compose-issue.md#second-issue
> doc: update instructions for starting containers

- Cargo.lock
- bombastic/index/src/lib.rs
- integration-tests/Cargo.toml
- integration-tests/src/bom.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/vexination.rs
- vexination/index/src/lib.rs
* Add a timestamp marking the time a document was indexed. This is generally useful to understand when a document was indexed both for debugging and for use by tests.
* Add unit test to verify the indexed timestamp.
* Add integration test to verify index is updated when updating a doc
> feat: add indexing timestamp

- deploy/compose/.env
- integration-tests/src/bom.rs
- integration-tests/src/config.rs
- integration-tests/src/lib.rs
- integration-tests/src/provider.rs
- integration-tests/src/spog.rs
- integration-tests/src/vex.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/vexination.rs
Fixes #401
Setting the `TRUST_URL` env var to a remote trustification server triggers the integs to be run against it.
If it's set, other env vars will be required:
- `TRUST_USER_ID` -- the client id of the user
- `TRUST_MANAGER_ID` -- the client id of the manager
- `TRUST_SECRET` -- the secret is assumed to be the same for user & mgr
If `KAFKA_BOOTSTRAP_SERVERS` is set, its value will be used to configure the event bus. Otherwise, SQS is assumed and valid AWS credentials will be required.
> feat: point the integs at a remote trustification server

- deploy/compose/compose-guac.yaml
- deploy/compose/compose-trustification.yaml
Here are some steps to test spog api guac integration
* Start everything
```
docker compose -f compose.yaml -f compose-guac.yaml -f compose-trustification.yaml up
```
* Get auth token
```
TOKEN=$(curl -s -d "client_id=walker" -d "client_secret=ZVzq9AMOVUdMY1lSohpx1jI3aW56QDPS" -d 'grant_type=client_credentials' \
'http://localhost:8090/realms/chicken/protocol/openid-connect/token' | jq -r .access_token)
```
* Ingest SBOM
```  
curl -v -H "transfer-encoding: chunked" --json @bombastic/testdata/ubi9-1750-sbom.json --oauth2-bearer $TOKEN  "http://localhost:8082/api/v1/sbom?id=my-sbom"
```
* Run some queries (dependencies, dependents, related packages)
```
curl -v -X GET --oauth2-bearer $TOKEN "http://localhost:8083/api/v1/packages/dependencies?purl=pkg:oci/registry.redhat./ubi9-container@sha2 …
```
> fix: compose connection between spog api and guac

- integration-tests/tests/bombastic.rs
- integration-tests/tests/vexination.rs
Ignores the tests that use the event bus for now since they require access to the internal infrastructure of trustification services in order to run.
> chore: enforce black box testing in integration tests

- api/src/search.rs
- bombastic/api/src/server.rs
- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- index/src/lib.rs
- integration-tests/tests/spog.rs
- spog/api/src/sbom.rs
- spog/model/src/search.rs
- spog/ui/src/backend/search.rs
- spog/ui/src/components/package.rs
- spog/ui/src/components/sbom/mod.rs
- vexination/api/src/server.rs
- vexination/index/src/lib.rs
In some cases, it is only interesting to know the number of hits/results for display purposes without actually showing the results. This adds a query flag summaries=true/false
(default true) which allows the client to discard document summaries to be fetched, with
the benefit of a faster search execution.
Issue #450
@ctron This should speed things up, but hold on the merge until I've done some more testing.
> feat: allow searching without fetching document summaries

- spog/ui/src/app.rs
- spog/ui/src/backend/mod.rs
This makes it easier to handle in the configuration, where injecting an array of string is rather complicated.
> refactor: use plain string for OIDC scope configuration

- Cargo.lock
- deploy/compose/.env
- index/Cargo.toml
- storage/Cargo.toml
Fixes #447
This branch of our fork cherry-picks PR's durch/rust-s3#353 and durch/rust-s3#343:
https://github.com/trustification/rust-s3/tree/trustification
The while loop mentioned in #447 runs for hours with this change. Without it, the loop fails usually in less than a minute.
> fix: race condition reading from s3

- spog/ui/src/components/advisory/search.rs
- spog/ui/src/components/sbom/mod.rs
- spog/ui/src/components/sbom/search.rs
- spog/ui/src/components/search/simple.rs
- spog/ui/src/hooks/search.rs
- spog/ui/src/pages/search.rs
This refactors out the common code of unified search, and with that adds a third option to the search results.
The third option searches SBOMs by dependency and acts as a guinea pig. We can drop it if we want.
> Refactor and add thrid option for unified result

- bombastic/api/src/lib.rs
- bombastic/indexer/src/lib.rs
- deploy/compose/compose-trustification.yaml
- exporter/src/lib.rs
- index/src/lib.rs
- integration-tests/src/bom.rs
- integration-tests/src/vex.rs
- storage/src/lib.rs
- vexination/api/src/lib.rs
- vexination/indexer/src/lib.rs
- vexination/walker/src/lib.rs
Previously the storage config was a mix of some env vars picked up by the underlying libraries. With this change all the required parameters are exposed as env vars and the k8s manifests will be updated to make use of it.
> chore: refactor storage config to expose a consistent set of parameters

- bombastic/api/src/lib.rs
- bombastic/api/src/server.rs
- index/Cargo.toml
- index/src/lib.rs
- vexination/api/src/lib.rs
- vexination/api/src/server.rs
- fix: reduce API latencies by removing unneeded storage lock
- fix: remove coarse grained index lock
Fixes #484
> fast index switch

- collector/osv/src/client/schema.rs
- collector/osv/src/lib.rs
when converting from OSV to v11y.
> Don't end up with double-escape-quoted reference types

- spog/api/src/config/default.yaml
- spog/api/src/config/mod.rs
- spog/model/schema/config.json
- spog/model/src/config.rs
- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/src/components/search/dynamic.rs
- spog/ui/src/components/search/simple.rs
This implements the missing "by time" filter options in the UI.
In contrast to the current sketches, this implementation uses checkboxes instead of radio buttons. This was decided after a chat with UX. Having radio buttons would actually limit the user into a single choice, and also create the problem of not being able to "unselect" a date range filter, unless we would add an "any" radio button. The resolution to those issues was to use checkboxes instead.
> Add options to search by time

- Cargo.lock
- bombastic/index/Cargo.toml
- bombastic/index/src/lib.rs
- index/Cargo.toml
- vexination/index/Cargo.toml
- vexination/index/src/lib.rs
This removes the need to keep separate fields for sorting ascending
> chore: upgrade tantivy

- bombastic/api/src/server.rs
- indexer/src/lib.rs
- storage/src/lib.rs
- vexination/api/src/server.rs
When walking a large number of objects, existing early because of a temporary network error
has some major implications on the rest of the system, such as needing to restart the process of walking the objects
or keeping tracked of the failed ones.
Instead, retry objects that failed to fetch a number of times before aborting.
> fix: retry objects that fail fetching to avoid failing retrieval process early

- bombastic/api/src/lib.rs
- index/src/lib.rs
- vexination/api/src/lib.rs
If the search index fails the initial sync, the readiness probe will not pass, which will
allow the previous instance of the API to continue working.
Issue #532
> feat: add readiness probe for API search availability

- Cargo.lock
- event-bus/src/kafka.rs
- event-bus/src/lib.rs
- event-bus/src/sqs.rs
- indexer/src/lib.rs
This ensures that processes using the event bus can get a hint whether they should treat the error as a critical or transient. For critical error, the indexer will exit.
> fix: introduce transient and critical error categories for event bus

- bombastic/indexer/src/lib.rs
- indexer/src/lib.rs
- integration-tests/src/bom.rs
- integration-tests/src/vex.rs
- vexination/indexer/src/lib.rs
The reindexing behavior is currently hardcoded to always or never, but this introduces another mode where reindexing can happen only if the index fails to load, which is typical for schema changes.
> feat: support different reindexing modes

- Cargo.lock
- bombastic/model/Cargo.toml
- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/common/Cargo.toml
- spog/ui/crates/components/Cargo.toml
- vexination/index/Cargo.toml
- vexination/model/Cargo.toml
For some the UI build fails with:
```
error: failed to build archive: 'wasm32.o': section too large
The following warnings were emitted during compilation:
warning: warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: /Users/baixiaofeng/workspace/trust-content/trustification/spog/ui/target/wasm32-unknown-unknown/debug/build/psm-fcac3221ee403c74/out/libpsm_s.a the table of contents is empty (no object file members in the library define global symbols)
error: could not compile `psm` (lib) due to previous error
```
This seems to becoming from `psm` -> `stacker` -> `chumsky` -> `sikula`.
To my understanding `psm` should be a no-op on WASM32, but it looks like mac os tooling falls over its feet and break the build. It works on Linux.
> Fix SPoG UI build on Mac OS

- bombastic/index/src/lib.rs
- bombastic/model/src/search.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/testdata/correlation/stf-1.5.json
The malformed test data prevented the SBOM from being ingested.
Add the ability to lookup by the original ID in bombastic search to ensure tests retrieve the correct document.
Issue #589
> fix: fix license in test data

- integration-tests/Cargo.toml
- integration-tests/src/bom.rs
- integration-tests/src/spog.rs
- integration-tests/src/vex.rs
- integration-tests/tests/bombastic.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/vexination.rs
Almost fixes #587 in that it will handle panics within the test bodies, but it will not handle a panic as a result of the `ntest::timeout` macro.
> fix: use the test context teardown fn to delete fixtures

- deploy/compose/container_files/init-sso/data/client-walker.json
This commit adds the read:document scope to the walker client.
The motivation for this change is that the walker client is used in the examples in DEVELOPING.md where it is used to create and read entries. Currently POSTing will work but trying to GET the same entry will result in an 403 forbidden error:
```console
$ curl -v -X POST --json @vexination/testdata/rhsa-2023_1441.json
--oauth2-bearer ... http://localhost:8081/api/v1/vex
...
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< content-length: 37
<
* Connection #0 to host localhost left intact
VEX of size 43885 stored successfully
$ curl -v -X GET --oauth2-bearer 'http://localhost:8081/api/v1/vex?advisory=RHSA-2023:1441'
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Bearer with user ''
> …
```
> fix: add read:document scope to walker client

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/vex.rs
- integration-tests/tests/spog.rs
This requires the index to be "always" rebuilt. Otherwise, the stale data in the index increments the advisory count with each test invocation.
> fix: make correlated doc id's truly unique

- integration-tests/Cargo.toml
- integration-tests/Containerfile
- integration-tests/src/bom.rs
- integration-tests/src/lib.rs
- integration-tests/src/spog.rs
- integration-tests/src/vex.rs
The feature flag is often forgotten and therefore breaks CI on some merges.
> fix: remove with-services feature to avoid breaking CI

- integration-tests/Cargo.toml
- integration-tests/Containerfile
- integration-tests/tests/bombastic.rs
- integration-tests/tests/spog.rs
- integration-tests/tests/vexination.rs
Acceptance tests are a subset of tests that can run successfully in a containerized environment against a production cluster
Also ignore unstable test (tracked in #618)
> Acceptance test feature flags

- collectorist/api/src/db/mod.rs
of purls to exlude any known-scanned recently enough.
> Add a method (unused currently) to filter an input set

- integration-tests/tests/vexination.rs
- vexination/api/src/server.rs
Since the vex api server loads the entire payload anyway, we'll parse the doc whether the id is sent or not, just to simplify the tests.
Bombastic validation will be a little trickier.
> fix: unignore empty vex tests

- bombastic/index/src/lib.rs
- index/src/lib.rs
- vexination/index/src/lib.rs
At present the new VEXes are not searchable because they are lacking a description.
Improve error message in log so it can be seen which field is missing
> fix: improve handling of new type of VEX without advisory description

- storage/src/lib.rs
Delete markers can be signalled if the buckets is configured to do so, which is the case for app-sre environment. This ensures that index deletion works as expected in those environments.
> fix: handle delete markers as delete events

- spog/api/src/cve.rs
- spog/model/src/cve.rs
- spog/ui/crates/backend/src/cve.rs
- spog/ui/src/pages/cve/result/mod.rs
- spog/ui/src/pages/cve/result/products.rs
The current endpoint `http://localhost:8083/api/v1/cve/{cve_id}` expects the following response body (this is mock data not real):
```
{
"id": "CVE_1",
"products": {
"fixed": [],
"first_fixed": [],
"first_affected": [],
"known_affected": [],
"last_affected": [],
"under_investigation": [
{
"sbom_id": "fuse-7.json.bz2",
"packages": [
{
"purl": "pkg:npm/acorn-import-assertions@1.8.0",
"type": "Direct"
},
{
"purl": "pkg:golang/github.com/petar/GoLLRB@v0.0.0-20130427215148-53be0d36a84c",
"type": "Transitive"
}
]
}
]
}
}
```
- From that I saw in @ctron 's code, the decision of setting "fixed|known_affected|under_investigation" will be taken from Vexination so no need to Guac to deal with it (anyone feel free to correct my assumptions if they are wrong)
- @dejanb GUAC needs to have something …
> Add related products table

- index/src/lib.rs
- vexination/index/src/lib.rs
* Allows each index to configure a tokenizer manager
* Enable an ngram (2, 64) tokenizer for vexination
> feat: enable ngram tokenizer for vexination

- spog/ui/crates/components/src/cve/mod.rs
- spog/ui/src/pages/cve/result/mod.rs
- spog/ui/src/pages/search.rs
- CVE table: rename "relations" by "Related products"
- Search view results: Move tab order to match mockups + hide "SbomsByPackage"
- CVE details page: Add "read more" link
> Spog UI - minor changes to align it to the mockups

- spog/ui/src/pages/sbom/mod.rs
- spog/ui/src/pages/sbom_report/mod.rs
- @ctron you created the "SbomReport" page which indeed follows the UX mockups. However, if we follow 100% the mockups we will trow away the other views that previously existed like "Sbom overview" + "Packages view" + "Source View"
- I don't think it is a good idea to throw away the good work done so far. So why don't we move the  "SbomReport" page you created and embedded it within the current "SbomPage" so it looks like the following image:
This way we are compliant with UX + we don't throw away previous work. And to me it looks much better visually. We can then talk with UX to ask their blessing. What do you think?
> Spog UI: Move "SbomReport" to "Sbom page"

- spog/ui/crates/components/src/common.rs
- spog/ui/crates/components/src/spdx/mod.rs
- spog/ui/src/pages/sbom/mod.rs
- Align card's height to make ui prettier
- SBOM "info" cards: order reorganized to allow card's full height
The following image is how it looks the current `main` branch, after this PR all cards' height should be the same.
> SpogUI: Align cards height to pretify visualization

- bombastic/index/src/lib.rs
- index/src/lib.rs
- v11y/index/src/lib.rs
- v11y/model/src/search.rs
- vexination/index/src/lib.rs
* Any field of type f64, u64, i64, date and bool can be sorted. Other types return error
* Remove sort annotation on CVE id string field
Fixes #663
> fix: ensure sorting can be done on any fast value type

- Cargo.lock
- Cargo.toml
- spog/api/src/cve.rs
- spog/api/src/guac/service.rs
Here's the draft PR for a replacing mock data with data from Guac.
It needs more testing, but for `rhel-7.9.z.json` sbom and `cve-2022-2284.json` vex it should return something like
```
{
"id": "cve-2022-2284",
"products": {
"KnownAffected": [
{
"sbom_id": "rhel-7.9.z",
"packages": [
{
"purl": "pkg:rpm/vim@7.4.629-8.el7_9?arch=src&epoch=2",
"type": "Direct"
}
]
}
]
},
"advisories": [],
"details": []
}
```
We should start testing it further and see what's still need to fixed for this.
To reproduce:
* Start trustification with with bombastic-api validator turned off (remove `--validator sbom`)
* Obtain the token
```
TOKEN=$(curl -s -d "client_id=walker" -d "client_secret=ZVzq9AMOVUdMY1lSohpx1jI3aW56QDPS" -d 'grant_type=client_credentials' \ …
```
> Product by CVE

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/backend/src/pkg.rs
- spog/ui/src/pages/cve/result/products.rs
In the related-products table we need to render `Version`, `Supplier`, and `Created on` columns which come from the SBOM index. This PR allows to fetch the SBOM index info for each row and render the corresponding data
> Spog UI: Related products - fetch sbom index info for each related product

- spog/api/src/cve.rs
Also set limit higher to catch multiple related advisories
> fix: skip fetching summaries for advisory count request

- spog/api/src/package.rs
- spog/ui/crates/backend/src/package_info.rs
https://github.com/trustification/trustification/pull/754 introduced `/api/v1/package_info` due to the fact that previously, we had the path `/api/v1/package` taken by other endpoints
- https://github.com/trustification/trustification/pull/776 renamed `/api/v1/package` by `/api/v1/sbom`
- This PR renames `/api/v1/package_info` by `/api/v1/package`
> task: Rename /package-info by /package

- spog/api/src/guac/service.rs
- spog/api/src/sbom/vuln.rs
- spog/api/src/server.rs
- spog/api/src/utils/spdx.rs
This PR changes the custom logic of extracting all PURLs and fetching information from GUAC one by one with the `find_vulnerabilities` method from guac-rs.
> refactor(spog): replace custom logic with `find_vulnerability`

- bombastic/index/src/lib.rs
- bombastic/indexer/src/lib.rs
- index/src/lib.rs
- indexer/src/lib.rs
- v11y/index/src/lib.rs
- v11y/indexer/src/lib.rs
- vexination/index/src/lib.rs
- vexination/indexer/src/lib.rs
Supporting multiple index stores allows a single indexer process to consume
a single document and index into separate index stores.
This PR has no changes to the existing behavior, and is a prereq for further work.
Issue #786, #784
> feat: support multiple index stores in indexer

- bombastic/index/src/lib.rs
- index/src/lib.rs
- storage/src/lib.rs
- v11y/index/src/lib.rs
- vexination/index/src/lib.rs
NOTE: This is a breaking change that will need a full reindex during update. The API should still serve the old index until the new is published.
Issue #784, #788
Requires #787  to be merged first.
> fix: support storing/loading multiple indexes from storage

- DEVELOPING.md
- deploy/konsole.tabs
- vexination/walker/src/lib.rs
- vexination/walker/src/server.rs
Also, add a KDE console tab-file, for starting up all services in a single step.
BREAKING-CHANGE: This no longer accepts `file:///` as a source URL but treats every non-URL as a path. Which allows using relative paths too.
> refactor: allow using a relative path

- exhort/api/src/server.rs
Change the starts_with() to consider the immediately-preceeding to_lowercase() when matching for CVEs.
> Add more schema to exhort openapi.

- spog/ui/src/console/mod.rs
When dedicated search is disabled, we still link to the details page from the unified search.
> fix: show package information even in any case

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/common/src/components/markdown.rs
- spog/ui/crates/common/src/components/mod.rs
- spog/ui/crates/components/Cargo.toml
- spog/ui/crates/components/src/advisory/mod.rs
- spog/ui/crates/components/src/advisory/search.rs
- spog/ui/crates/components/src/common.rs
- spog/ui/crates/components/src/cve/search.rs
- spog/ui/crates/components/src/hooks/search.rs
- spog/ui/crates/components/src/lib.rs
- spog/ui/crates/components/src/packages/search.rs
- spog/ui/crates/components/src/sbom/search.rs
- spog/ui/crates/components/src/search/simple.rs
- spog/ui/src/console/mod.rs
- spog/ui/src/pages/cve/result/mod.rs
- spog/ui/src/pages/search.rs
So far, we did store the page state in the browser history. However,
when unpacking it (on hitting "back"), the defaults did override any
selection made by the user so far.
This change fixes this by tracking both the "modification" state as well
as the "defaults" which need to get applied. Also when the user
resets the search.
> fix: don't let the default override any use made changes on "back"

- Cargo.lock
- admin/Cargo.toml
- admin/src/delete.rs
- admin/src/upload.rs
- index/src/lib.rs
* Add devmode to simplify usage of admin upload and admin delete
* Add ability to pass custom headers when uploading
* Bump default memory available to index when running locally
@ctron just a few convenience changes as I was trying out the quarkus sbom/vex data
> feat: add devmode to upload and delete

- bombastic/index/src/packages/mod.rs
- bombastic/model/src/packages/mod.rs
- spog/api/src/endpoints/package.rs
- spog/model/src/package_info.rs
- spog/model/src/search.rs
- spog/ui/crates/backend/src/package_info.rs
- spog/ui/crates/components/src/packages/mod.rs
- spog/ui/crates/components/src/packages/search.rs
- spog/ui/src/pages/package/result/vulnerabilities.rs
* Allow searching explicitly for "namespace" and "name" of the PURL
* Drop the `PackageInfoSummary` structure, it seemed like a copy
* Drop the "description" field, I don't think we will ever have this
> refactor: some package index improvements

- deploy/openshift/parameters.yaml
- deploy/openshift/template.yaml
Unquoting is handled by double curly for non-string types.
> fix: parameters must be passed as string

- deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
This makes it easier to maintain the guac-user-db secret not having to know the hostname of an RDS instance.
> fix: get host and port from admin db

- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
Deleting documents from bombastic will not delete entries from the packages index, because packages are unique and index does not keep relationship to the SBOM (since multiple SBOMs may contain the same package).
As a workaround, reindexing the bombastic index on startup will allow the package index to be rebuilt upon a restart from the SBOMs that exist in the archive.
@ctron @bxf12315 Any thoughts or concerns on this? Maybe it's possible to add some kind of 'ref-counting' of the package in a separate index field eventually?
> fix: always reindex bombastic at startup

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/backend/Cargo.toml
- spog/ui/crates/common/Cargo.toml
- spog/ui/crates/components/Cargo.toml
- spog/ui/crates/utils/Cargo.toml
- spog/ui/src/pages/cve/result/mod.rs
Came out of a discussion on patternfly-yew … while the implementation is correct (at least when ignoring grapheme clusters), the outcome is not optimal: 
* Markdown cannot be rendered
* Not all characters have the same width
That's we the "expandable section" using the "truncate" variants seems like the better approach. It will truncate after 3 lines. Which gives a more stable visual result.
> refactor: replace custom truncation with ExpandableSection

- index/src/lib.rs
- spog/api/src/endpoints/cve.rs
- spog/api/src/endpoints/sbom/vuln/vex.rs
- vexination/index/src/lib.rs
ngrams already get converted to lowercase. That's why I think it doesn't
make sense allowing uppercase characters. But instead lowercase the
search terms too, so that we can get a match.
This also means a different to other (string) fields, where we search
for string data, not "text". Those string fields don't use the ngram
mode.
> refactor: perform lowercase search

- container_files/Containerfile.services
The main reason is the improvement on trunk's ability to generate SRI attributes.
> chore: update frontend tooling

- spog/api/src/config/default.yaml
- spog/model/schema/config.json
- spog/model/src/config.rs
- spog/ui/src/console/mod.rs
*Suggestion: remove the Github (source code link) from the downstream distribution.*
The mockups don't have the Github link and although useful in upstream, I value not to show everything on downstream (just a personal opinion). Feel free to reject this PR.
- This PR adds a new config value `downstream` to be re-used at any part of the UI
> task: set the Github repository code configurable

- container_files/Containerfile.services
- spog/api/src/config/default.yaml
- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/README.md
- spog/ui/src/export.rs
- spog/ui/src/main.rs
**NOTE:** This change requires that one updates `trunk` or `trunk-ng` to a version of `trunk-ng 0.17.16` or newer.
> fix: allow navigating to the scanner without reloading the page

- container_files/Containerfile.services
- spog/ui/config/nginx.conf
- spog/ui/dev/trunk-hook.sh
- spog/ui/index.html
* Branding is expected to be found under /branding
* The local /branding folder will be copied to /branding-default by trunk
* A trunk hook will duplicate that directory to /branding in local development mode
* Nginx will be configured to resolve /branding resources first from /branding, then falling back to /branding-default
This way it is possible to perform easy local testing, and have the deployment override the branding resources (which are mounted into /branding), but still leverage the defaults from /branding-default.
> fix: try a better way to handle branding assets

- deploy/openshift/database-recreate-template.yaml
This is the example of the template that could be used downstream to recreate postgres database.
I contains a job with 3 containers:
1. Drop database
2. Init database
3. Run Guac migration
It needs the following parameters:
* PG_IMAGE
* PG_IMAGE_TAG
* GUAC_IMAE
* GUAC_IMAGE_TAG
Hopefully after running this job, we don't even need to restart Guac
> [!WARNING]
> This has not been tested!
I'm not sure how to best test/iterate over this without disrupting environments.
> feat: provide a template to recreate postgres database

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/components/src/download.rs
- spog/ui/src/analytics/mod.rs
- spog/ui/src/main.rs
- spog/ui/src/pages/index.rs
- spog/ui/src/pages/scanner/inspect.rs
- spog/ui/src/pages/scanner/mod.rs
- spog/ui/src/pages/scanner/upload.rs
- spog/ui/src/pages/search.rs
We need to put the analytics code at one single point and avoid spreading of "event names" as much as we can.
The idea is to put all "event keys" in one single place so it is easier for us to keep good naming convention. I suggest also following good practices described at https://segment.com/docs/getting-started/implementation-guide/#event-anatomy-and-naming-standards 
```
Segment recommends the best practice of using an “Object Action” (Noun Verb)
naming convention for all Track events (for example, Menu Clicked)
```
> [TC-770] - Consolidate Analytics

- exhort/api/src/server.rs
This is just a small fix to the regex so it can catch versions like `2.13.8.Final-redhat-00004`. Note that it is not `.redhat-xxxxx`.
With this change I get the found packages.
```
{
"recommendations": {
...
"pkg:maven/io.quarkus/quarkus-vertx-http@2.13.8.Final-redhat-00004": [
{
"package": "pkg:maven/io.quarkus/quarkus-vertx-http@2.13.8.Final-redhat-00004?repository_url=https://maven.repository.redhat.com/ga/&type=jar",
"vulnerabilities": []
},
{
"package": "pkg:maven/io.quarkus/quarkus-vertx-http@2.13.8.Final-redhat-00005?repository_url=https://maven.repository.redhat.com/ga/&type=jar",
"vulnerabilities": []
}
]
}
}
```
> fix: change regex to catch more red hat related patterns

- deploy/k8s/chart/templates/spog/ui/030-Deployment.yaml
- deploy/openshift/parameters.yaml
- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
Add an option to inject the initial backend json value before processing it.
We do require this to enable the external consent setting.
> feat: allow setting the initial backend JSON

- Cargo.lock
- Cargo.toml
upgrade guac_rs to fix `find_vulnerability_statuses function` to work with certify vex/vuln directly
> fix: upgrade guac_rs to fix find_vulnerability_statuses function

- bombastic/index/src/packages/mod.rs
- bombastic/index/src/sbom/mod.rs
- index/src/lib.rs
- v11y/index/src/lib.rs
- vexination/index/src/lib.rs
The Debug implementation of the Regexp query dumps the regexp instruction set, which can be rather long and is not really useful.
> chore: lower query logging to trace, limit regexp state output

- bombastic/index/src/packages/mod.rs
- bombastic/model/src/packages/mod.rs
We need to search by architecture, like this: `qualifier:arch:aarch64`
> feat: allow searching packages by qualifier

- spog/ui/crates/components/src/advisory/mod.rs
- spog/ui/crates/components/src/download.rs
- spog/ui/crates/components/src/sbom/mod.rs
Currently there are 2 components that serve the "downloads"
- <Download/> used in the main tabs tables. I added the "type" field of this event and enhance the event key
- <LocalDownloadButton/> used in the page details of each entity "Advisory", "Sbom", "CVE"
Both need to be consistent in naming and in properties
> Enhance download tracking data

- deploy/k8s/chart/templates/init-dataset/030-CronJob.yaml
- deploy/openshift/parameters.yaml
- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
Configurable job to run manually the dataset in case of needed. Currently exists a job executed only after a deploy.
> Dataset configurable cronjob

- auth/src/client/provider/openid.rs
- bombastic/walker/src/lib.rs
This is required as CRC doesn't have proper certificates.
> feat: allow switching TLS to insecure for the OIDC provider too

- v11y/index/src/lib.rs
- v11y/walker/src/lib.rs
This is **not** a fix for #1025, but might fall back to 3.0 and shows the vector it failed to parse
> fix: fall back to 3.0 score when we can't parse 3.1

- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/components/src/advisory/search.rs
- spog/ui/crates/components/src/analytics.rs
- spog/ui/crates/components/src/cve/search.rs
- spog/ui/crates/components/src/lib.rs
- spog/ui/crates/components/src/packages/search.rs
- spog/ui/crates/components/src/sbom/search.rs
- spog/ui/crates/components/src/search/dynamic.rs
- spog/ui/crates/components/src/search/simple.rs
- spog/ui/crates/utils/src/analytics/mod.rs
- v11y/index/src/lib.rs
- v11y/walker/src/lib.rs
This is mainly adding the analytics tracking for changes to the filter.
- [fix: fall back to 3.0 score when we can't parse 3.1](https://github.com/trustification/trustification/pull/1029/commits/4cfd9ade78fa29bf4b56e841e99a2f868218912f)
- [chore: show prefixes when running](https://github.com/trustification/trustification/pull/1029/commits/2543d1fb6f9d1aa348d3c4e80eaf803e7ce5eddc)
- [feat: add tracking events for filter controls](https://github.com/trustification/trustification/pull/1029/commits/8e5a47c638ddcdef46410f3c65b5bde3baaf5368)
> [stable] analytics tracking for changes to the filter

- spog/api/src/app_state.rs
- spog/api/src/endpoints/sbom/mod.rs
- spog/api/src/endpoints/sbom/post.rs
- spog/ui/crates/backend/src/sbom.rs
- spog/ui/crates/components/src/download.rs
- spog/ui/crates/navigation/src/lib.rs
- spog/ui/src/console/mod.rs
- spog/ui/src/pages/mod.rs
- spog/ui/src/pages/sbom/mod.rs
- spog/ui/src/pages/scanner/mod.rs
- spog/ui/src/pages/scanner/upload.rs
- spog/ui/src/pages/uploader/inspect.rs
- spog/ui/src/pages/uploader/mod.rs
- Uploads an sbom using the same patterns as "scan sbom"
- Each sbom details have now the "reports" tab wich invokes crds to generate the reports
- Each SBOM will have the ID generated by uuid (we can discuss this)
- **Yet to do**:  Fetch the list of sboms every 5 seconds to update the table ui so the user sees his sbom when it is ready after being indexed.
> feat: Upload SBOM

- bombastic/indexer/src/lib.rs
- index/src/lib.rs
- indexer/src/lib.rs
CP of https://github.com/trustification/trustification/pull/1038
When reindexing, the indexes are "reset", which basically means that new indexes are being created. However, the loop still holds on to the old writers. So when resetting the indexes, we must also create new writers.
Otherwise the logic will write to the old indexes, and the new ones will stay empty.
Only the following commits must be merged backported:
* 239e44b6209c664d18e005310ce880d94cd4a7af
* 931b16c1d2b7037c9febb231c99d8654b3de839f
* 3eecb8659bd75f9ed726a59b6f68e66dd355fe8e
* 7e82ad9010556be122fb6d41e8abc24d11659879 (actual fix)
---
Also, this changes the DS1 `csaf` layout to the new file system layout
> [stable] Cherry-pick relevant commits of PR #1038

- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
Within RHSSO we have a scope `api.trusted_content` assigned. After contacting the RHSSO team, they have set up the scope `api.trusted_content` so we will get the ORG_ID claim if the scope `api.trusted_content` is requested while doing the auth flow.
I'd like to deploy this to https://trustification.stage.devshift.net/ . Should I open this PR directly on the `stable` branch?
> task: Request api.trusted_content scope to get orgId

- .tekton/trustification-service-release.yaml
Results watcher logs have been throwing a lot of "reconcile error" - 
```
{"level":"error","ts":"2024-02-05T11:52:51.162Z","logger":"watcher","caller":"controller/controller.go:566","msg":"Reconcile error","knative.dev/traceid":"92bf1cfc-18b6-46fa-abfe-97bc1318686e","knative.dev/key":"trusted-content-tenant/trustification-service-release-s6ddf","duration":"5.540319796s","error":"error patching object: admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed: invalid value: pipeline task \"clone-repository\" expects workspace with name \"git-auth\" but none exists in pipeline spec: spec[1].workspaces[1]","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/opt/app-root/src/vendor/knative.dev/pkg/controller/controller.go:566\nknative.dev/pk …
```
> define git-auth workspace for release PipelineRun

- Cargo.lock
- auth/Cargo.toml
- auth/schema/auth.json
- auth/src/authenticator/claims.rs
- auth/src/authenticator/config.rs
- auth/src/authenticator/mod.rs
- auth/src/authenticator/user.rs
- auth/src/authorizer/mod.rs
Aside from renaming to `additional_permissions` (which should still be a non-breaking change due to the alias) that shouldn't change the current behavior. But it allows to extract groups and map those into permissions too.
> feat: allow using groups as source for permissions

- DEVELOPING.md
- VSCODE.md
VSCode is a very popular Open Source IDE.
This adds details to setup VScode to help navigate the source and debug the code in line.
We could also commit the ./vscode/settings.json` file containing all the Trustification packages upfront.
See the debugging feature in action :
[Screencast from 2024-02-08 14-50-56.webm](https://github.com/trustification/trustification/assets/1901741/521729a7-00a9-4607-a6c0-556c0e8b1be8)
> Add VSCode IDE support

- spog/ui/src/pages/search/mod.rs
Currently we are sending the previous tab selected, while we should send the tab that has just been selected. This PR will fix it
> fix: Tab selection event data

- .github/workflows/containers.yaml
- container_files/Containerfile.git
- container_files/Containerfile.services
Adding git and postgresql client on the default image. In this way we can skip the maintenance of the git image and the use of postgresql server image used only from a cronjob.
> Adding git and postgresql client on the default image

- deploy/compose/.env
- deploy/k8s/legacy/values-crc.yaml
- deploy/k8s/legacy/values-minikube.yaml
- deploy/k8s/legacy/values-openshift-blueprint.yaml
- deploy/trustification.dev/dev.yaml
- deploy/trustification.dev/prod.yaml
- deploy/trustification.dev/staging.yaml
Bump guac container image to v0.3.27 
Supports https://github.com/trustification/trustification/pull/1082
Partially supersedes https://github.com/trustification/trustification/pull/1092
> Bump guac image to v0.3.27

- index/src/lib.rs
- v11y/index/src/lib.rs
- v11y/testdata/CVE-2023-44487.json
- vexination/index/src/lib.rs
I checked the other indexes for case-insensitive search. We might want to discuss SBOMs and packages separately.
For CVEs (v11y), we can enable this. But as the data didn't get indexed in the require format before, that change would require re-indexing the full CVE data. We can do that, but I would prefer to do this after the release. I don't think the added value makes up for the risk we're adding at this point.
So I'll leave this open as a draft PR.
Also see: https://issues.redhat.com/browse/TC-894
> feat: allow case-insensitive searching for v11y as well

- deploy/k8s/charts/trustification/templates/helpers/_guac.tpl
- deploy/k8s/charts/trustification/templates/services/guac/bombastic-collector/030-Deployment.yaml
- deploy/k8s/charts/trustification/templates/services/guac/vexination-collector/030-Deployment.yaml
Currently there's no root certificates set for the Guac clients (both graphql and grpc).
This should help with TC-1025
> fix: add root certification to guac clients

- deploy/k8s/charts/trustification/templates/helpers/_storage.tpl
This fixes the warning:
```
spec.template.spec.containers[0].env[3].name: duplicate name "STORAGE_REGION"
```
> fix: only have the env-var once

- vexination/index/src/lib.rs
- vexination/model/src/search.rs
searching of a partial string of a CVE ID will yield results from v11y, but no from vexination. This change aligns that behavior.
> fix: align the search capabilities of CVE with advisories

- vexination/index/src/lib.rs
- vexination/model/src/search.rs
searching of a partial string of a CVE ID will yield results from v11y, but no from vexination. This change aligns that behavior.
> [release/1.0.z] fix: align the search capabilities of CVE with advisories

- index/src/lib.rs
- spog/model/src/search.rs
- spog/ui/crates/components/src/advisory/mod.rs
- spog/ui/src/pages/cve/result/advisories.rs
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
The aggregated severity is optional. If we don't have it, skipping the document is not the right way to deal with this.
> fix: allow the aggregated severity to be omitted

- index/src/lib.rs
- spog/model/src/search.rs
- spog/ui/crates/components/src/advisory/mod.rs
- spog/ui/src/pages/cve/result/advisories.rs
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
The aggregated severity is optional. If we don't have it, skipping the document is not the right way to deal with this.
> [release/1.0.z] fix: allow the aggregated severity to be omitted

- vexination/index/src/lib.rs
This is required as we need the ID to look up the document at a later time. So we need to know the original, exact ID.
Should only be merged after #1173 is merged.
> [release/1.0.z] fix: store a raw/unaltered version of the ID

- vexination/index/src/lib.rs
- vexination/testdata/lowercase-id.json
The recent change which keeps the case of the ID stable did not consider that we also use the advisory ID of the document as an internal document ID. So keeping the case of the original ID would no longer match the advisory ID, which we need to uppercase, in order to get case insensitive search.
> fix: don't create duplicates in the index when re-uploading a document

- vexination/index/src/lib.rs
- vexination/testdata/lowercase-id.json
The recent change which keeps the case of the ID stable did not consider that we also use the advisory ID of the document as an internal document ID. So keeping the case of the original ID would no longer match the advisory ID, which we need to uppercase, in order to get case insensitive search.
> [release/1.0.z] fix: don't create duplicates in the index when re-uploading a document

- container_files/Containerfile.docs
- container_files/Containerfile.services
* chore: upgrade to trunk 0.19.0 musl and use ubi image
* chore: use plain ubi9 image for the docs build
> [release/1.0.z] chore: upgrade to trunk 0.19.0 musl and use ubi image (#1194)

- spog/ui/src/pages/package/result/related_products.rs
https://issues.redhat.com/browse/TC-1051
I've seen that the "backstraces" field was never implemented and always return an empty array. As a consequence we always have an empty expandable section in the "package details => products using package" table.
This is the line where the `backstraces are set` https://github.com/trustification/trustification/blob/main/spog/api/src/service/guac.rs#L321
```rust
backtraces: vec![]
```
So it makes sense to me just to disable the expandable section for all rows as we don't expect to see data there.
> fix: Remove expandable "products using" package in "Package details" page

- spog/ui/crates/components/src/cyclonedx/mod.rs
- spog/ui/src/pages/sbom/mod.rs
https://issues.redhat.com/browse/TC-1061
- The specVersion seems not to be part of the SBOM object, therefore I needed to parse the json and read the `specversion` field manually
- Replace `Serial number` by `Serial Number` to align it to the other fields pattern
> Render cyclonedx spec version on the info tab within the sbom detail page

- deploy/k8s/charts/trustification/templates/services/guac/graphql/050-NetworkPolicy.yaml
Improve network policy for guac, so that it blocks the ingress for the graphql port, but allows access to metrics port.
> fix: allow access to metrics port to monitoring stack

- spog/ui/crates/common/src/error/components.rs
- spog/ui/crates/common/src/error/mod.rs
- spog/ui/src/pages/sbom_report/mod.rs
https://issues.redhat.com/browse/TC-1091
- Enhance error state component:
- The main branch renders the error icon next to the error message (left to right)
- This PR sets the error icon on top of the error message following the Patternfly patterns and examples https://www.patternfly.org/extensions/component-groups/error-boundary
> Enhance error component and set hardcoded message when guac fails on "related advisories"

- spog/api/src/config/mod.rs
- spog/api/src/server.rs
- spog/ui/crates/backend/src/config.rs
- spog/ui/crates/utils/src/config/components.rs
- spog/ui/src/app.rs
- spog/ui/src/console/mod.rs
Some part of the configuration might be considered confidential. So we do remove most of the configuration information and create a dedicated, public endpoint.
> fix: provide a way to retrieve public vs non-public frontend config

- Cargo.lock
- bombastic/api/src/server.rs
- indexer/src/lib.rs
- integration-tests/tests/vexination.rs
- storage/Cargo.toml
- storage/src/key.rs
- storage/src/lib.rs
- v11y/api/src/server/vulnerability.rs
- v11y/walker/src/lib.rs
- vexination/api/src/server.rs
The key has a direct impact on the path inside the S3 bucket. We must ensure that the user is not able to influence the location of the file, only the name of it.
This change ensures that they user provided key does not contain any character that might have an in impact on the location inside the bucket.
> fix: ensure that the storage key does not alter the path structure

- spog/api/src/config/mod.rs
- spog/api/src/server.rs
- spog/ui/crates/backend/src/config.rs
- spog/ui/crates/utils/src/config/components.rs
- spog/ui/src/app.rs
- spog/ui/src/console/mod.rs
Some part of the configuration might be considered confidential. So we do remove most of the configuration information and create a dedicated, public endpoint.
> [release/1.0.z] fix: provide a way to retrieve public vs non-public frontend config

- spog/ui/src/pages/vex_uploader/mod.rs
Consistency with SBOM `Upload another` label
https://github.com/trustification/trustification/blob/621fc8abc1b67a25686e635a1f9ac5319a845b82/spog/ui/src/pages/uploader/mod.rs#L112
> Fix: CSAF/VEX 'Upload another' label

- docs/modules/admin/pages/cluster-install.adoc
Enhance documentation to help users in identifying the endpoints mentioned above.
Preview at https://github.com/mrizzi/trustification/blob/add-command-urls/docs/modules/admin/pages/cluster-install.adoc
> Docs: add command to get URLs to accept in the browser

- spog/ui/crates/components/src/advisory/details/mod.rs
- spog/ui/crates/components/src/advisory/details/product.rs
https://issues.redhat.com/browse/TC-1224
- Make the Product tree component not expanded by default
- Switch CsafProductStatus to use the "overview" visualization, otherwise big advisories also kills the browser
> [TC-1224] Avoid frozing browser on big advisory details

- deploy/compose/compose-guac.yaml
- deploy/k8s/charts/trustification-infrastructure/values.yaml
It's handy to have config like this ready to use when someone wants to debug database operations
> chore: add option to set additional postgres configuration

- spog/api/src/config/mod.rs
- spog/ui/src/about.rs
- https://issues.redhat.com/browse/TC-1237 : spog-api: expose features in the public api
- The features define which pages are going to be present; given the current hierarchy of components, the code that renders the pages only has access to the "public" configuration and not to the private one. This PR exposes also the features as part of the public api. The features are a set of boolean values which I don't consider to be a security thread to expose. I accept different opinions though.
```json
"features": {
"scanner": false,
"uploader": false,
"extendSection": true,
"dedicatedSearch": false,
"additionalPackageInformation": false,
"showSource": false,
"showReport": true
},
```
https://github.com/trustification/trustification/blob/f158e8354c0d56d7424ee15322c1930791f068b6/spog/ui/src/consol …
> [TC-1237] [TC-1248] ui: about model to use public config & expose features in the public api

- collector/osv/src/lib.rs
- collector/snyk/src/lib.rs
Build GuacClient with provided reqwest::Client to manage TLS with ClientConfig
Backport https://github.com/trustification/trustification/pull/1353
> [release/1.0.z] GuacClient to manage TLS

- Cargo.lock
- spog/api/Cargo.toml
- spog/ui/Cargo.toml
- spog/ui/crates/backend/Cargo.toml
- v11y/index/Cargo.toml
Backport https://github.com/trustification/trustification/pull/1364
Fixes https://issues.redhat.com/browse/TC-1495
> [release/1.0.z] Bump cve 0.3.0

- spog/ui/src/pages/package/result/vulnerabilities.rs
- spog/ui/src/pages/sbom_report/details/mod.rs
- Package details page, `Vulnerabilites` tab
- applied the `Show more` to description field
- made `NoWrap` the CVE ID and publish date fields (consistent with the `sbom_report` product details page)
- ensure `CVSS` column's with is 15% (consistent with the `sbom_report` product details page)
- Product details page, `Related advisories` tab: applied the `Show more` to description field
> TC1177: enhance CVE UI components

- spog/ui/Cargo.lock
- spog/ui/crates/components/src/advisory/search.rs
- spog/ui/crates/components/src/search/toolbar.rs
Restore (as previously used with value of 0) fetch_interval to avoid user to browse page.
Fix https://issues.redhat.com/browse/TC-1225
> fix: [TC-1225] - When opening an advisory to see its attributes, the display jumps to the top of the page

- deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
- deploy/k8s/chart/templates/init-guac/020-Job.yaml
- deploy/openshift/database-recreate-template.yaml
- deploy/openshift/parameters.yaml
- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
Both OIDC and guac secret use the hardcoded values. This commit make the values configurable using template parameter.
> Use template params for OIDC and guac db secret

- spog/ui/Cargo.lock
- spog/ui/crates/components/src/search/toolbar.rs
https://issues.redhat.com/browse/TC-1225
Backport:
- https://github.com/trustification/trustification/pull/1372
> [release/1.1.z] TC-1225 When opening an advisory to see its attributes, the display jumps to the top of the page

- Cargo.lock
- Cargo.toml
Backport:
- https://github.com/trustification/trustification/pull/1397
> [release/1.1.z] chore: bump guac-rs to v0.3.0

- spog/ui/crates/components/src/advisory/details/remediation.rs
- spog/ui/styles/main.scss
https://issues.redhat.com/browse/TC-1263
How to reproduce the issue:
- Start this repo without the changes into this PR
- Upload a CSAF file [CVE-2023-44487.json](https://github.com/user-attachments/files/15787154/CVE-2023-44487.1.json)
- Open the advisory details page and navigate to the "Vulnerabilities" tab. There expand the table rows. Inside the expanded area of the tables you should see a "Remediations" section, expand it and you will see the text is overflowing the white area
After applying this PR, you can follow the same steps and the issue should be gone.
> [TC-1263][SPoG-UI] - When opening a 'vendor fix' in a CVE ID under an advisory, the data is cut off

- Cargo.lock
- spog/api/Cargo.toml
- spog/ui/Cargo.lock
- spog/ui/Cargo.toml
- spog/ui/crates/backend/Cargo.toml
- v11y/index/Cargo.toml
Backport:
- https://github.com/trustification/trustification/pull/1398
> [release/1.1.z] chore: update cve to 0.3.1

- spog/ui/Cargo.lock
Backports:
- https://github.com/trustification/trustification/pull/1446
Bumps [curve25519-dalek](https://github.com/dalek-cryptography/curve25519-dalek) from 4.1.2 to 4.1.3.
- [Release notes](https://github.com/dalek-cryptography/curve25519-dalek/releases)
- [Commits](https://github.com/dalek-cryptography/curve25519-dalek/compare/curve25519-4.1.2...curve25519-4.1.3)
---
updated-dependencies:
- dependency-name: curve25519-dalek dependency-type: indirect ...
> [release/1.1.z] build(deps): bump curve25519-dalek from 4.1.2 to 4.1.3 in /spog/ui

- .tekton/trustification-service-pull-request.yaml
- .tekton/trustification-service-push.yaml
- .tekton/trustification-tests-pull-request.yaml
- .tekton/trustification-tests-push.yaml
These parameters will make it so that the sast task starts uploading sarif results to quay.io, for long-term storage.
Related: https://issues.redhat.com/browse/KONFLUX-2263
> Upload SAST results

- .tekton/trustification-product-1-0-z-pull-request.yaml
- .tekton/trustification-product-1-0-z-push.yaml
- .tekton/trustification-product-test-1-0-z-pull-request.yaml
- .tekton/trustification-product-test-1-0-z-push.yaml
These parameters will make it so that the sast task starts uploading sarif results to quay.io, for long-term storage.
Related: https://issues.redhat.com/browse/KONFLUX-2263
see: https://github.com/trustification/trustification/pull/1512
> Upload SAST

- spog/ui/src/pages/sbom/mod.rs
https://issues.redhat.com/browse/TC-1578
The updated label and tooltip look like:
> TC-1578 Enhanced Vulnerabilities tab labels

- bombastic/model/src/data.rs
- bombastic/testdata/sbom-without-serialNumber.cyclonedx.json
- storage/src/validator.rs
https://issues.redhat.com/browse/TC-1619
Added validation for the presence of a value for the `serialNumber` field in the case the SBOM is a CycloneDX one.
As reported in the related issue, the  `serialNumber` field is option in CycloneDX 1.4 [specifications](https://cyclonedx.org/docs/1.4/json/) but it's mandatory for trustification to properly manage correlations.
The change covers, at once, both the UI and the API.
On the UI side, the failure in validating appears like any other validation failure during an SBOM upload, i.e. at the bottom of the upload page
On the API side, the call returns, just like for any other validation failure, an `HTTP/1.1 400 Bad Request` response (with details logging).
Added also multiple tests for covering this change but also some positive validation for …
> TC-1619 SBOM CycloneDX serialNumber validation

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
This PR should fix two things:
- Revert back from building arm images CI workflow as it's not needed and it makes PR checks very long
- It seems that podman is still pushing only the first manifest. Comparing to the trustify build which works properly, the only difference that I see is the usage of `--all` argument. I would try that first and if it doesn't work switch to using `redhat-actions/push-to-registry@v2` action
> fix: arm build improvements

- deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml
- deploy/k8s/chart/templates/init-guac/020-Job.yaml
- deploy/k8s/chart/templates/postgres/030-Deployment.yaml
- deploy/openshift/database-recreate-template.yaml
- deploy/openshift/parameters.yaml
- deploy/openshift/template.yaml
- deploy/openshift/values.yaml
* Use template params for OIDC and guac db secret (#1396)
Both OIDC and guac secret use the hardcoded values. This commit make the values configurable using template parameter.
* Set TC_PGOPTIONS using chart variable
The TC_PGOPTIONS was the only variable which was using the hardcoded value. This change makes it configurable using params.
---------
> Use template params for OIDC and guac db secret (#1436)

- collector/osv/src/client/mod.rs
- collector/osv/src/client/schema.rs
https://issues.redhat.com/browse/TC-1714
Updated (and sorted for ease of maintenance) the `Ecosystem` enum to reflect the allowed values in the upstream OSV schema (ref. [`Ecosystem`](https://github.com/ossf/osv-schema/blob/fca1c1348935a71bb5e93159d462b9828894c5df/validation/schema.json#L303))
> TC-1714 Enhanced Ecosystem enum

- bombastic/model/src/data.rs
- bombastic/testdata/syft.cyclonedx.newline.json
This PR workarounds the problem caused by https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/737 which doesn't allow control characters in the CyclonDX Json fields although that is allowed by the specification.
This PR replaces control characters with space. It also
* Upgrades the lib to the 0.7.0 version
* Improves error handling in the process
TBD:
* Include test that demonstrates the issue
* Check for side-effects
* Clean and improve the code
> fix: allow control characters in CyclonDX JSON fields

- admin/src/lib.rs
- bombastic/bombastic/src/lib.rs
- collector/collector/src/lib.rs
- collectorist/collectorist/src/lib.rs
- exhort/exhort/src/lib.rs
- v11y/v11y/src/lib.rs
- vexination/vexination/src/lib.rs
Related to #1127 
```console
Trust
Usage: trust <COMMAND>
Commands:
vexination    Run vexination services (`trust vexination --help` for details)
bombastic     Run bombastic services (`trust bombastic --help` for details)
spog          Single Pane of Glass
exhort        Run exhort services (`trust exhort --help` for details)
collectorist  Run collectorist services (`trust collectorist --help` for details)
collector     Run collector services (`trust collector --help` for details)
v11y          Run v11y services (`trust v11y --help` for details)
exporter      Run the exporter
admin         Run admin services (`trust admin --help` for details)
help          Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
> fix: adds description for remaining commands

- collector/osv/src/client/mod.rs
OSV isn't providing information for previously working CVE IDs used in `query_vuln_ecosystem_ubuntu` test causing failures like https://github.com/trustification/trustification/actions/runs/10578469221/job/29308681073?pr=1713#step:10:1566
New vulnerabilities affecting the whole set of Ubuntu versions have been identified.
> Found new vulnerabilties for testing Ubuntu ecosystem

- bombastic/api/src/server.rs
- bombastic/index/src/sbom/mod.rs
- bombastic/model/src/search.rs
- index/src/lib.rs
- integration-tests/tests/bombastic.rs
- v11y/api/src/server/search.rs
- v11y/index/src/lib.rs
- v11y/model/src/search.rs
- vexination/api/src/server.rs
- vexination/index/src/lib.rs
- vexination/model/src/search.rs
https://issues.redhat.com/browse/TC-1668
This issue is caused by Tantivy's insufficient time precision when handling dates.
1 How to reproduce it.
you can run unit test on [here](This test aims to prove that sorting can be done using indexed_timestamp. )(https://github.com/trustification/trustification/blob/main/bombastic/index/src/sbom/mod.rs#L755)
and got result 
`
> name: "kmm-1"  indexed_timestamp: 2024-09-23 6:39:09.070292 +00:00:00 created : 2023-06-26 11:24:00.0 +00:00:00
> name: "ubi9-sbom"  indexed_timestamp: 2024-09-23 6:39:09.162848 +00:00:00 created : 2023-03-30 13:59:00.0 +00:00:00
> name: "my-sbom"  indexed_timestamp: 2024-09-23 6:39:09.108631 +00:00:00 created : 2023-02-14 10:46:37.0 +00:00:00
`
but the order is not right. ubi9-sbom.json is last updated.
2 The reason after …
> [TC-1668] - Dashboard - Status panel - back end - Correct the issue of incorrect timestamp sorting

- spog/ui/crates/components/src/spdx/mod.rs
https://issues.redhat.com/browse/TC-1815
As reported in the related Jira issue, currently the "Info" tab in the SBOM details page could "waste" a lot of space just like in the next screenshot.
With the changes, the "Package" box looks like this (with the "Package" box properly ending before the end of the page)
> TC-1815 SBOM details page: enhance 'Info' tab formatting

- collector/osv/src/server.rs
- collectorist/api/src/coordinator/collector.rs
https://issues.redhat.com/browse/TC-1818
Basically the fix address the happy path when OSV returns vulnerabilties referring already to their CVE ID, in which case there's no need any further call to OSV itself to retrieve the aliases and to then ingest "vulnEqual" entities into Guac.
As a "bonus" fix, during the development I've figured out that a collectorist API log entry reports for each single PURL all the vulnerabilities found for all the PURLs in the same request instead of just logging the vulnerabilities related to that specific PURL so I've fixed it to ease future investigations.
For example, previously it was
`
[osv] scanned pkg:deb/debian/tar@1.34+dfsg-1.2?arch=amd64&distro=debian-12 [["CVE-2023-24329", "CVE-2023-27043", "CVE-2023-40217", "CVE-2023-41105", "CVE-2023-6597", …
> TC-1818 Collector OSV: fix 'CVE' prefixed vulnerabilities management

- collector/osv/src/server.rs
- collectorist/api/src/coordinator/collector.rs
https://issues.redhat.com/browse/TC-1818
Backport:
- https://github.com/trustification/trustification/pull/1778
> [release/1.2.z] TC-1818 Collector OSV: fix 'CVE' prefixed vulnerabilities management

- docs/modules/admin/examples/trustification/database.tf
tofu script fails for,
- RDS cert authority
- VPC filter with `kubernetes.io/role/internal-elb`
> Update on cert and tags

- spog/ui/src/pages/index.rs
- spog/ui/src/pages/search/search_input.rs
https://issues.redhat.com/browse/TC-1839
The image below is how it should look like.
This PR only:
- Aligns the Search input text to the left
- Make the Input Search placeholder to match the mockups
All the other changes should be done in the Helm Chart Definition
> [TC-1839] - Change TPA home page

- bombastic/index/src/packages/mod.rs
- bombastic/testdata/openssl-3.0.7-18.el9_2.spdx.json
https://issues.redhat.com/browse/TC-1757
SPDX SBOM allows a package to have multiple PURLs listed in the `externalRefs` array. Since in trustification's index each document is related to one PURL, the document should be created per purl (so within the `package.external_reference.iter()` loop) rather than externally.
> TC-1757 SPDX: manage multiple PURLs per package

- bombastic/index/src/sbom/mod.rs
- bombastic/testdata/my-sbom.json
- spog/ui/crates/components/src/cyclonedx/mod.rs
- spog/ui/src/pages/sbom/mod.rs
https://issues.redhat.com/browse/TC-1842
Consistently with what already implemented for SPDX SBOM details page, I've added the `Package` card also to the CycloneDX SBOM details page in order to report the CPE information (together with all the other external references).
The final result is something like this:
Furthermore, for consistency, I've added the `cpe` field also to the index (with test) when indexing a CycloneDX SBOM just like it already happens for the SPDX SBOM in https://github.com/trustification/trustification/blob/18910f498096e07ca22ca6591aa612ca014fbb91/bombastic/index/src/sbom/mod.rs#L185
> TC-1842 CycloneDX CPE management

- deploy/k8s/charts/trustification/templates/services/v11y/walker/030-CronJob.yaml
The container macro used a wrong indentation and was placed in a wrong spot.
> Fix: update an indentation of container in v11y-walker

- spog/api/src/endpoints/sbom/search.rs
This will backport the following commits from `main` to `release/1.2.z`:
- [TC-1819: reverse search order to find last 10 sboms ingested (#1841)](https://github.com/trustification/trustification/pull/1841)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [release/1.2.z] TC-1819: reverse search order to find last 10 sboms ingested (#1841)

- v11y/walker/src/lib.rs
https://issues.redhat.com/browse/TC-1865
There was an issue: when more prefixes were provided, e.g. `CVE-2023-` and `CVE-2024-`, when a file to be analyzed was evaluated, e.g. `CVE-2023-1234.json`, it would match with the first prefix, i.e. `CVE-2023-`, the condition `if !name.starts_with(prefix)` would have been `false`, meaning to not skip that file and analyze it, but with the next iteration of the `for` loop, with the `CVE-2024-` prefix, the  condition `if !name.starts_with(prefix)` would have been `true` and the `continue 'entry;` statement then executed which would make the  `CVE-2023-1234.json` to be skipped which is the bug.
> TC-1865 Fix multiple prefixes management

- v11y/walker/src/lib.rs
https://issues.redhat.com/browse/TC-1865
the v11y walker was ignoring all CVE files in a source folder if no prefix parameter was supplied
> TC-1865: Prevent all cve files being ignored without prefix input

- spog/ui/src/about.rs
- version/src/lib.rs
https://issues.redhat.com/browse/TC-1892
Following the strategy of https://github.com/trustification/trustification/pull/2088 and https://github.com/trustification/trustification/pull/2089 this PR is hardcoding the version provided in the endpoint `.well-known/trustification/version` which currently always returns `0.1.0` ( this value is wrong)
After this changes the response of the endpoint should be similar to:
```json
{
"name": "spog-api",
"version": "main",
"description": "An API server for trusted content",
"git": {
"describe": "v0.1.0-nightly.420e67b0-2681-g72d645d2-dirty",
"commit": "72d645d2563dc3361a1decfe512ecc8e04d33153"
},
"build": {
"timestamp": "2024-12-09T09:48:26.734823656Z"
}
}
```
> The main branch will always have `version=main` and all the other branches should have …
> [TC-1892] fix: hardcoded provided version on API

- spog/api/src/endpoints/sbom/search.rs
- spog/api/src/endpoints/sbom/vuln/analyze.rs
- spog/api/src/endpoints/sbom/vuln/mod.rs
- spog/ui/crates/backend/src/sbom.rs
- spog/ui/src/pages/index.rs
- spog/ui/src/pages/sbom_report/mod.rs
https://issues.redhat.com/browse/TC-1970
`/api/v1/sbom/latestwithvulns`
- retrieval of vulnerabilities concurrently (instead of current serial approach) for the 10 SBOMs in scope for the Dashboard bars chart
- dropped `process_get_vulnerabilities` usage (i.e. avoid downloading each SBOM and each CVE JSON each time from S3-compatible storage) in favor of using search indexes
- retrieved CVE info from `v11y.search` in bulk of 25 CVEs
`/api/v1/sbom/vulnerabilities`
- added the `retrieve_remediation` param to the `get_vulnerabilities` endpoint used by the four donut charts in the dashboard in order to avoid loading the remediation because there are useless for those charts (but still required in the `Vulnerabilities` tab in the SBOM details page) and changed the UI components accordingly
- …
> TC-1970 Dashboard: enhance vulnerabilities retrieval

- collector/osv/src/client/schema.rs
- collector/osv/src/server.rs
https://issues.redhat.com/browse/TC-2022
- enhanced the schema to work with `CVSS_V4` value for severity type
- refactored the severity and score management:
- `CVSSv3` management remains the same, i.e. `cvss_v3s.push(cvss);` but in case of error in getting the score then it's logged with a warn message
- all other severity types got reported with a warning log
> TC-2022 Fix OSV CVSS_V4 severity type ingestion

- docs/modules/admin/examples/trustification/database.tf
As tofu script failed for psql version 15.5, updating the version to 16.3 referring to AWS
Screenshots from tofu script run for reference:
> Updating tofu script PSQL version to 16.3

- spog/ui/src/about.rs
- version/src/lib.rs
This PR will change the version hard-coded in the UI About modal and also on the `.well-known/trustification/version` endpoint from spog-api
https://issues.redhat.com/browse/TC-2089
> [release/1.2.z][TC-2089]: fix: update version to 1.2.2

- spog/ui/src/about.rs
- version/src/lib.rs
This PR will change the version hard-coded in the UI About modal and also on the `.well-known/trustification/version` endpoint from spog-api
> [release/1.3.z] fix: update version to 1.3.0

- spog/ui/src/pages/sbom/mod.rs
- spog/ui/src/pages/scanner/mod.rs
https://issues.redhat.com/browse/TC-1978
- Remove the Tab "Dependency analytics Report" from the SBOM Page details
- Remove the Warning message when an SBOM is uploaded because the warning message refers to Dependency Analytics supported packages
> [TC-1978] task: remove dependency analytics

- v11y/index/src/lib.rs
- v11y/testdata/CVE-2023-6260.json
Backport of https://github.com/trustification/trustification/pull/2144
https://issues.redhat.com/browse/TC-1710
> [release/1.3.z][TC-1710] Inconsistent visuals when a CVE has multiple CVSS scores (#2144)

- spog/ui/crates/components/src/cvss.rs
- spog/ui/src/pages/cve/result/mod.rs
Backport of https://github.com/trustification/trustification/pull/2148
https://issues.redhat.com/browse/TC-1710
> [release/1.3.z][TC-1710] - The CVE details page should get the score/severity from the index as the only source of truth (#2148)

- spog/ui/src/pages/sbom/mod.rs
https://issues.redhat.com/browse/TC-2182
Also referenced in https://issues.redhat.com/browse/TC-1978?focusedId=26496176&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26496176
In the issue, the [screenshot](https://issues.redhat.com/secure/attachment/13342161/image-2025-01-29-10-22-29-363.png) shows the slow requests are `Stalled` and the reasons behind are explained in [Timing breakdown phases explained](https://developer.chrome.com/docs/devtools/network/reference/?utm_source=devtools#timing-explanation) which clarifies is something that happens on the browser.
This situation is confirmed also by the server's log where those requests have fast execution times (some milliseconds).
This `queueing` situations always started after the SBOM details page was …
> TC-2182 Avoid ReportViewwer fetching data

- spog/api/src/license/license_exporter.rs
- spog/api/src/license/license_scanner.rs
A single PR to fix multiple issues since they're all related since they affect the license export:
- https://issues.redhat.com/browse/TC-2150
- https://issues.redhat.com/browse/TC-2160
- https://issues.redhat.com/browse/TC-2187
- https://issues.redhat.com/browse/TC-2212
- https://issues.redhat.com/browse/TC-2213
Where possible and meaningful I commented to clarify which change covers which issue.
I've also fixed the modification time for the CSV files that otherwise would have been EPOCH but, in this way, the user knows when the file has been created.
Furthermore I've refactored the code, mainly `generate_csvs`, in order to be able to create some tests to cover all of the issues with some tests.
> TC-2150 TC-2160 TC-2187 TC-2212 TC-2213 License export issues

- spog/ui/src/pages/index.rs
https://issues.redhat.com/browse/TC-2219
The width of the div that wraps the Chart should change automatically but with a limit. So setting the `max-width` prop rather than `width`.
https://github.com/user-attachments/assets/b1ba05e7-250a-4724-b1fa-a3e5369cb212
> [TC-2219] fix: When changing zoom in the Home screen, the pie charts are overlapping their boarders

- spog/ui/src/pages/index.rs
Backport of https://github.com/trustification/trustification/pull/2165
https://issues.redhat.com/browse/TC-2219
> [release/1.3.z][TC-2219] fix: When changing zoom in the Home screen, the pie charts are overlapping their boarders (#2165)

- Cargo.lock
- Cargo.toml
https://issues.redhat.com/browse/TC-2279
Backports:
- https://github.com/trustification/trustification/pull/2183
> [release/1.3.z] TC-2279 Bump guac 0.7.2-1
